# The CSV Module
In this notebook, you'll learn:
1. How to read files
2. How to use the CSV reader method

There's no better way to learn this than by actually exploring a .csv file. I chose to explore the [2023 Data Scientists' Salaries](https://www.kaggle.com/datasets/henryshan/2023-data-scientists-salary) and conducted data analysis towards the end of the notebook. The dataset includes the following variables:

```work_year```: The year the salary was paid.


```experience_level```: The experience level in the job during the year.

```EN``` > Entry-level / Junior

```MI``` > Mid-level / Intermediate

```SE``` > Senior-level / Expert

```EX``` > Executive-level / Director


```employment_type```: The type of employment for the role.

```PT``` > Part-time

```FT``` > Full-time

```CT``` > Contract

```FL``` > Freelance


```job_title```: The role worked in during the year.


```salary```: The total gross salary amount paid.


```salary_currency```: The currency of the salary paid as an ISO 4217 currency code.


```salary_in_usd```: The salary in USD.


```employee_residence```: Employee's primary country of residence during the work year as an ISO 3166 country code.


```remote_ratio```:The overall amount of work done remotely.


```company_location```: The country of the employer's main office or contracting branch.


```company_size```: The median number of people that worked for the company during the year.

## Opening a file
---

One can use Python to open a file, be it .jpeg, .txt or .pdf. Our focus is the .csv file, so we'll stick to that. But first, let's look at Python's inbuilt function that can be used to open, read and write files -- [```open()```](https://docs.python.org/3/library/functions.html#open).

The ```open()``` function can take in 8 arguments, but only 1 is mandatory, the file name.

```py
open(file, mode='r', buffering=- 1, encoding=None, errors=None, newline=None, closefd=True, opener=None)
```

While the function can take in 8 arguments, we'll focus on 2:
* file - This is the file path of the file. When the file is in the same directory as your folder, then you can simply specify the name of the file you want to open, written as a string e.g ```"ds_salaries.csv"```. This is a mandatory argument and must be specified.
* mode - This tells python how it should open the file, based on your intentions. When not specified, it defaults to ```'r'``` which stands for  "read (only)" mode. Other modes include:

| Character | Meaning |
| --- | --- |
| ```'r'``` | open for reading (default) |
| ```'w'``` | open for writing, truncating the file first |
| ```'x'``` | open for exclusive creation, failing if the file already exists |
| ```'a'``` | open for writing, appending to the end of file if it exists |
| ```'b'``` | binay mode |
| ```'t'``` | textmode (default) |
| ```'+'``` | open for updating (reading and writing)  |

As you can see, you can open a file in may other modes apart from ```r```. Be careful when opening the file in "write" mode, ```w```, as this deletes everything that was in the file to enable you to write in it. If you want to add to the file without deleting its contents, you should use the "append" mode, ```a``` 

Once you are done with the file, it is imperative that you close it to avoid wasting the system's resources. Yes, even if you are using your big company's servers with the latest GPUs (I'm talking to you MAANG employees!).

Ok, now let's see all this in code.

In [40]:
f = open("ds_salaries.csv")
file_data = f.read()
f.close()

print(file_data)

work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
2023,SE,FT,Principal Data Scientist,80000,EUR,85847,ES,100,ES,L
2023,MI,CT,ML Engineer,30000,USD,30000,US,100,US,S
2023,MI,CT,ML Engineer,25500,USD,25500,US,100,US,S
2023,SE,FT,Data Scientist,175000,USD,175000,CA,100,CA,M
2023,SE,FT,Data Scientist,120000,USD,120000,CA,100,CA,M
2023,SE,FT,Applied Scientist,222200,USD,222200,US,0,US,L
2023,SE,FT,Applied Scientist,136000,USD,136000,US,0,US,L
2023,SE,FT,Data Scientist,219000,USD,219000,CA,0,CA,M
2023,SE,FT,Data Scientist,141000,USD,141000,CA,0,CA,M
2023,SE,FT,Data Scientist,147100,USD,147100,US,0,US,M
2023,SE,FT,Data Scientist,90700,USD,90700,US,0,US,M
2023,SE,FT,Data Analyst,130000,USD,130000,US,100,US,M
2023,SE,FT,Data Analyst,100000,USD,100000,US,100,US,M
2023,EN,FT,Applied Scientist,213660,USD,213660,US,0,US,L
2023,EN,FT,Applied Scientist,130760,USD,130760,US,0,US,L
2023,SE,FT,Data Modeler,147100,USD,147100,US,0,US,M
2023,SE,FT,Data Modeler,90700,USD,90700,US,0,US,M
2023,SE,FT,Data Scientist,170000,USD,170000,US,0,US,M
2023,SE,FT,Data Scientist,150000,USD,150000,US,0,US,M
2023,MI,FT,Data Analyst,150000,USD,150000,US,100,US,M
2023,MI,FT,Data Analyst,110000,USD,110000,US,100,US,M
2023,SE,FT,Research Engineer,275000,USD,275000,DE,0,DE,M
2023,SE,FT,Research Engineer,174000,USD,174000,DE,0,DE,M
2023,SE,FT,Analytics Engineer,230000,USD,230000,GB,100,GB,M
2023,SE,FT,Analytics Engineer,143200,USD,143200,GB,100,GB,M
2023,SE,FT,Business Intelligence Engineer,225000,USD,225000,US,0,US,M
2023,SE,FT,Business Intelligence Engineer,156400,USD,156400,US,0,US,M
2023,SE,FT,Machine Learning Engineer,200000,USD,200000,US,0,US,M
2023,SE,FT,Machine Learning Engineer,130000,USD,130000,US,0,US,M
2023,SE,FT,Data Strategist,90000,USD,90000,CA,0,CA,M
2023,SE,FT,Data Strategist,72000,USD,72000,CA,0,CA,M
2023,SE,FT,Data Engineer,253200,USD,253200,US,0,US,M
2023,SE,FT,Data Engineer,90700,USD,90700,US,0,US,M
2023,SE,FT,Computer Vision Engineer,342810,USD,342810,US,0,US,M
2023,SE,FT,Computer Vision Engineer,184590,USD,184590,US,0,US,M
2023,MI,FT,Data Engineer,162500,USD,162500,US,0,US,M
2023,MI,FT,Data Engineer,130000,USD,130000,US,0,US,M
2023,MI,FT,Data Analyst,105380,USD,105380,US,0,US,M
2023,MI,FT,Data Analyst,64500,USD,64500,US,0,US,M
2023,EN,FT,Data Quality Analyst,100000,USD,100000,NG,100,NG,L
2023,EN,FT,Compliance Data Analyst,30000,USD,30000,NG,100,NG,L
2022,MI,FT,Machine Learning Engineer,1650000,INR,20984,IN,50,IN,L
2023,EN,FT,Applied Scientist,204620,USD,204620,US,0,US,L
2023,EN,FT,Applied Scientist,110680,USD,110680,US,0,US,L
2023,SE,FT,Data Engineer,270703,USD,270703,US,0,US,M
2023,SE,FT,Data Engineer,221484,USD,221484,US,0,US,M
2023,SE,FT,Data Scientist,212750,USD,212750,US,100,US,M
2023,SE,FT,Data Scientist,185000,USD,185000,US,100,US,M
2023,SE,FT,Data Scientist,262000,USD,262000,US,100,US,M
2023,SE,FT,Data Scientist,245000,USD,245000,US,100,US,M
2023,SE,FT,Data Scientist,275300,USD,275300,US,100,US,M
2023,SE,FT,Data Scientist,183500,USD,183500,US,100,US,M
2023,SE,FT,Data Scientist,218500,USD,218500,US,100,US,M
2023,SE,FT,Data Scientist,199098,USD,199098,US,100,US,M
2023,SE,FT,Data Engineer,203300,USD,203300,US,100,US,M
2023,SE,FT,Data Engineer,123600,USD,123600,US,100,US,M
2023,SE,FT,Research Engineer,189110,USD,189110,US,0,US,M
2023,SE,FT,Research Engineer,139000,USD,139000,US,0,US,M
2023,EX,FT,Data Scientist,258750,USD,258750,US,0,US,M
2023,EX,FT,Data Scientist,185000,USD,185000,US,0,US,M
2023,SE,FT,Data Engineer,231500,USD,231500,US,100,US,M
2023,SE,FT,Data Engineer,166000,USD,166000,US,100,US,M
2023,SE,FT,Data Scientist,172500,USD,172500,US,100,US,M
2023,SE,FT,Data Scientist,110500,USD,110500,US,100,US,M
2023,SE,FT,Data Engineer,238000,USD,238000,US,0,US,M
2023,SE,FT,Data Engineer,176000,USD,176000,US,0,US,M
2023,SE,FT,Data Engineer,237000,USD,237000,US,100,US,M
2023,SE,FT,Data Engineer,201450,USD,201450,US,100,US,M
2023,SE,FT,Applied Scientist,309400,USD,309400,US,0,US,L
2023,SE,FT,Applied Scientist,159100,USD,159100,US,0,US,L
2023,SE,FT,Data Engineer,115000,USD,115000,US,0,US,M
2023,SE,FT,Data Engineer,81500,USD,81500,US,0,US,M
2023,SE,FT,Data Scientist,237000,USD,237000,US,100,US,M
2023,SE,FT,Data Scientist,201450,USD,201450,US,100,US,M
2023,SE,FT,Computer Vision Engineer,280000,USD,280000,US,0,US,M
2023,SE,FT,Computer Vision Engineer,210000,USD,210000,US,0,US,M
2023,SE,FT,Data Architect,280100,USD,280100,US,100,US,M
2023,SE,FT,Data Architect,168100,USD,168100,US,100,US,M
2023,SE,FT,Data Engineer,193500,USD,193500,US,100,US,M
2023,SE,FT,Data Engineer,139000,USD,139000,US,100,US,M
2023,MI,FT,Data Scientist,510000,HKD,65062,HK,0,HK,L
2023,SE,FT,Machine Learning Engineer,150000,USD,150000,PT,100,US,M
2023,MI,FT,Applied Machine Learning Engineer,65000,EUR,69751,IN,100,DE,S
2022,EN,FT,AI Developer,300000,USD,300000,IN,50,IN,L
2023,MI,FT,Machine Learning Engineer,90000,EUR,96578,NL,100,NL,L
2023,SE,FT,Business Intelligence Engineer,185900,USD,185900,US,0,US,M
2023,SE,FT,Business Intelligence Engineer,129300,USD,129300,US,0,US,M
2023,SE,FT,Data Engineer,225000,USD,225000,US,100,US,M
2023,SE,FT,Data Engineer,175000,USD,175000,US,100,US,M
2023,SE,FT,Data Engineer,185000,USD,185000,US,0,US,M
2023,SE,FT,Data Engineer,140000,USD,140000,US,0,US,M
2023,SE,FT,Data Scientist,45000,EUR,48289,ES,0,ES,M
2023,SE,FT,Data Scientist,36000,EUR,38631,ES,0,ES,M
2023,SE,FT,Data Scientist,105000,USD,105000,US,0,US,M
2023,SE,FT,Data Scientist,70000,USD,70000,US,0,US,M
2023,EN,FT,Machine Learning Engineer,163196,USD,163196,US,0,US,M
2023,EN,FT,Machine Learning Engineer,145885,USD,145885,US,0,US,M
2023,SE,FT,Data Engineer,217000,USD,217000,US,100,US,M
2023,SE,FT,Data Engineer,185000,USD,185000,US,100,US,M
2023,SE,FT,Data Analyst,202800,USD,202800,US,0,US,L
2023,SE,FT,Data Analyst,104300,USD,104300,US,0,US,L
2023,SE,FT,Data Analyst,145000,USD,145000,US,0,US,M
2023,SE,FT,Data Analyst,65000,USD,65000,US,0,US,M
2023,SE,FT,Data Engineer,165000,USD,165000,US,0,US,M
2023,SE,FT,Data Engineer,132300,USD,132300,US,0,US,M
2023,SE,FT,Data Engineer,179170,USD,179170,US,0,US,M
2023,SE,FT,Data Engineer,94300,USD,94300,US,0,US,M
2023,SE,FT,Analytics Engineer,152500,USD,152500,US,0,US,M
2023,SE,FT,Analytics Engineer,116450,USD,116450,US,0,US,M
2023,SE,FT,Data Engineer,247300,USD,247300,US,0,US,M
2023,SE,FT,Data Engineer,133800,USD,133800,US,0,US,M
2023,SE,FT,Research Engineer,203000,USD,203000,US,0,US,M
2023,SE,FT,Research Engineer,133000,USD,133000,US,0,US,M
2023,EN,FT,Research Scientist,220000,USD,220000,US,50,US,L
2022,EN,FT,Machine Learning Engineer,54000,CHF,56536,CH,100,CH,S
2023,SE,FT,Data Scientist,150000,USD,150000,US,0,US,M
2023,SE,FT,Data Scientist,120000,USD,120000,US,0,US,M
2023,SE,FT,Analytics Engineer,289800,USD,289800,US,0,US,M
2023,SE,FT,Analytics Engineer,214000,USD,214000,US,0,US,M
2023,SE,FT,Analytics Engineer,179820,USD,179820,US,0,US,M
2023,SE,FT,Analytics Engineer,143860,USD,143860,US,0,US,M
2023,SE,FT,Machine Learning Engineer,283200,USD,283200,US,100,US,M
2023,SE,FT,Machine Learning Engineer,188800,USD,188800,US,100,US,M
2023,SE,FT,Analytics Engineer,289800,USD,289800,US,0,US,M
2023,SE,FT,Analytics Engineer,214200,USD,214200,US,0,US,M
2023,SE,FT,Data Engineer,185900,USD,185900,US,0,US,M
2023,SE,FT,Data Engineer,129300,USD,129300,US,0,US,M
2023,SE,FT,Data Engineer,252000,USD,252000,US,0,US,M
2023,SE,FT,Data Engineer,129000,USD,129000,US,0,US,M
2023,MI,FT,Data Analytics Manager,155000,USD,155000,US,0,US,M
2023,MI,FT,Data Analytics Manager,140000,USD,140000,US,0,US,M
2023,SE,FT,Data Engineer,161800,USD,161800,US,100,US,M
2023,SE,FT,Data Engineer,141600,USD,141600,US,100,US,M
2023,SE,FT,Machine Learning Engineer,342300,USD,342300,US,0,US,L
2023,SE,FT,Machine Learning Engineer,176100,USD,176100,US,0,US,L
2023,MI,FT,Data Engineer,100000,USD,100000,US,100,US,M
2023,MI,FT,Data Engineer,70000,USD,70000,US,100,US,M
2023,EN,FT,Data Engineer,85000,USD,85000,US,0,US,M
2023,EN,FT,Data Engineer,65000,USD,65000,US,0,US,M
2023,SE,FT,Data Scientist,138784,USD,138784,US,100,US,M
2023,SE,FT,Data Scientist,83270,USD,83270,US,100,US,M
2023,EN,FT,Data Analyst,75000,USD,75000,US,0,US,M
2023,EN,FT,Data Analyst,70000,USD,70000,US,0,US,M
2023,SE,FT,Data Analyst,204500,USD,204500,US,0,US,M
2023,SE,FT,Data Analyst,138900,USD,138900,US,0,US,M
2023,SE,FT,Machine Learning Engineer,318300,USD,318300,US,100,US,M
2023,SE,FT,Machine Learning Engineer,212200,USD,212200,US,100,US,M
2023,SE,FT,Data Engineer,95000,USD,95000,US,100,US,M
2023,SE,FT,Data Engineer,75000,USD,75000,US,100,US,M
2023,SE,FT,Data Scientist,195000,USD,195000,US,0,US,M
2023,SE,FT,Data Scientist,160000,USD,160000,US,0,US,M
2023,SE,FT,Analytics Engineer,230000,USD,230000,US,0,US,M
2023,SE,FT,Analytics Engineer,143200,USD,143200,US,0,US,M
2023,MI,FT,Data Engineer,100000,USD,100000,US,100,US,M
2023,MI,FT,Data Engineer,70000,USD,70000,US,100,US,M
2023,MI,FT,Business Data Analyst,105000,USD,105000,US,50,US,L
2023,MI,FT,Applied Data Scientist,1700000,INR,20670,IN,100,IN,L
2023,MI,FT,Data Analyst,38000,GBP,46178,GB,0,GB,M
2023,MI,FT,Data Analyst,35000,GBP,42533,GB,0,GB,M
2023,SE,FT,Data Engineer,145000,USD,145000,US,0,US,M
2023,SE,FT,Data Engineer,115000,USD,115000,US,0,US,M
2023,SE,FT,Data Analyst,168400,USD,168400,US,0,US,M
2023,SE,FT,Data Analyst,105200,USD,105200,US,0,US,M
2023,SE,FT,Applied Scientist,309400,USD,309400,US,0,US,L
2023,SE,FT,Applied Scientist,159100,USD,159100,US,0,US,L
2023,SE,FT,Machine Learning Engineer,190000,USD,190000,US,0,US,M
2023,SE,FT,Machine Learning Engineer,150000,USD,150000,US,0,US,M
2023,MI,FT,Data Engineer,162500,USD,162500,US,0,US,M
2023,MI,FT,Data Engineer,130000,USD,130000,US,0,US,M
2023,SE,FT,Analytics Engineer,150000,USD,150000,US,100,US,M
2023,SE,FT,Analytics Engineer,120000,USD,120000,US,100,US,M
2023,SE,FT,Data Engineer,145000,USD,145000,US,0,US,M
2023,SE,FT,Data Engineer,120000,USD,120000,US,0,US,M
2023,SE,FT,Applied Scientist,222200,USD,222200,US,0,US,L
2023,SE,FT,Applied Scientist,136000,USD,136000,US,0,US,L
2023,SE,FT,Data Analyst,45000,GBP,54685,CF,100,CF,M
2023,SE,FT,Data Analyst,35000,GBP,42533,CF,100,CF,M
2023,SE,FT,Data Engineer,241000,USD,241000,US,0,US,M
2023,SE,FT,Data Engineer,155000,USD,155000,US,0,US,M
2023,SE,FT,Data Engineer,220000,USD,220000,US,100,US,M
2023,SE,FT,Data Engineer,190000,USD,190000,US,100,US,M
2023,MI,FT,Data Scientist,55000,GBP,66837,GB,0,GB,M
2023,MI,FT,Data Scientist,45000,GBP,54685,GB,0,GB,M
2020,EX,FT,Staff Data Analyst,15000,USD,15000,NG,0,CA,M
2023,MI,FT,ETL Engineer,70000,GBP,85066,GB,100,GB,M
2023,MI,FT,ETL Engineer,47500,GBP,57723,GB,100,GB,M
2023,EN,FT,Data Analyst,85000,USD,85000,US,100,US,M
2023,EN,FT,Data Analyst,75000,USD,75000,US,100,US,M
2023,SE,FT,Data Engineer,160000,USD,160000,US,0,US,M
2023,SE,FT,Data Engineer,140000,USD,140000,US,0,US,M
2023,MI,FT,Machine Learning Engineer,300000,USD,300000,US,0,US,M
2023,MI,FT,Machine Learning Engineer,250000,USD,250000,US,0,US,M
2023,SE,FT,Data Scientist,228000,USD,228000,US,0,US,M
2023,SE,FT,Data Scientist,186000,USD,186000,US,0,US,M
2023,SE,FT,Data Scientist,190000,USD,190000,US,0,US,M
2023,SE,FT,Data Scientist,170000,USD,170000,US,0,US,M
2023,MI,FT,Research Engineer,230000,USD,230000,US,0,US,M
2023,MI,FT,Research Engineer,200000,USD,200000,US,0,US,M
2023,SE,FT,Data Architect,180000,USD,180000,US,100,US,M
2023,SE,FT,Data Architect,115000,USD,115000,US,100,US,M
2023,SE,FT,Data Architect,200000,USD,200000,US,100,US,M
2023,SE,FT,Data Architect,115000,USD,115000,US,100,US,M
2023,SE,FT,Data DevOps Engineer,50000,EUR,53654,FR,50,FR,S
2023,EX,FT,Data Engineer,220000,USD,220000,US,0,US,M
2023,EX,FT,Data Engineer,205000,USD,205000,US,0,US,M
2023,MI,FT,Data Engineer,180000,USD,180000,US,0,US,M
2023,MI,FT,Data Engineer,130000,USD,130000,US,0,US,M
2023,SE,FT,Data Engineer,200000,USD,200000,US,100,US,M
2023,SE,FT,Data Engineer,150000,USD,150000,US,100,US,M
2023,SE,FT,Computer Vision Engineer,215000,USD,215000,US,0,US,M
2023,SE,FT,Computer Vision Engineer,170000,USD,170000,US,0,US,M
2023,SE,FT,Machine Learning Engineer,247500,USD,247500,US,0,US,M
2023,SE,FT,Machine Learning Engineer,172200,USD,172200,US,0,US,M
2023,SE,FT,Data Scientist,224000,USD,224000,CA,0,CA,M
2023,SE,FT,Data Scientist,176000,USD,176000,CA,0,CA,M
2023,SE,FT,Data Analyst,120000,USD,120000,US,100,US,M
2023,SE,FT,Data Analyst,75000,USD,75000,US,100,US,M
2023,EN,FT,Data Engineer,1400000,INR,17022,IN,100,IN,L
2023,SE,FT,Applied Data Scientist,100000,AUD,68318,AU,100,FI,M
2023,MI,FT,AI Developer,100000,SGD,75020,FI,0,FI,M
2023,SE,FT,Data Analyst,140000,USD,140000,US,0,US,M
2023,SE,FT,Data Analyst,120000,USD,120000,US,0,US,M
2023,SE,FT,Data Engineer,128000,USD,128000,US,0,US,M
2023,SE,FT,Data Engineer,81500,USD,81500,US,0,US,M
2023,SE,FT,Data Engineer,145000,USD,145000,US,0,US,M
2023,SE,FT,Data Engineer,115000,USD,115000,US,0,US,M
2023,SE,FT,Data Engineer,185000,USD,185000,US,0,US,M
2023,SE,FT,Data Engineer,140000,USD,140000,US,0,US,M
2023,EX,FT,Head of Data,329500,USD,329500,US,0,US,M
2023,EX,FT,Head of Data,269600,USD,269600,US,0,US,M
2023,SE,FT,Data Quality Analyst,100000,USD,100000,US,0,US,M
2023,SE,FT,Data Quality Analyst,80000,USD,80000,US,0,US,M
2023,SE,FT,Data Scientist,250000,USD,250000,US,0,US,M
2023,SE,FT,Data Scientist,162500,USD,162500,US,0,US,M
2023,MI,FT,AI Developer,200000,USD,200000,US,100,US,M
2023,SE,FT,Data Engineer,145000,USD,145000,US,0,US,M
2023,SE,FT,Data Engineer,100000,USD,100000,US,0,US,M
2023,EX,FT,Data Engineer,145000,USD,145000,US,0,US,M
2023,EX,FT,Data Engineer,115000,USD,115000,US,0,US,M
2023,SE,FT,Data Scientist,203500,USD,203500,US,0,US,M
2023,SE,FT,Data Scientist,152000,USD,152000,US,0,US,M
2023,SE,FT,Data Scientist,239000,USD,239000,US,0,US,L
2023,SE,FT,Data Scientist,122900,USD,122900,US,0,US,L
2023,SE,FT,Data Scientist,237000,USD,237000,US,0,US,M
2023,SE,FT,Data Scientist,145000,USD,145000,US,0,US,M
2023,SE,FT,Data Science Manager,191765,USD,191765,US,0,US,M
2023,SE,FT,Data Science Manager,134236,USD,134236,US,0,US,M
2023,SE,FT,Analytics Engineer,190000,USD,190000,US,100,US,M
2023,SE,FT,Analytics Engineer,112000,USD,112000,US,100,US,M
2022,SE,FT,Data Scientist,84000,EUR,88256,ES,100,GB,L
2023,EN,FT,Data Engineer,85000,USD,85000,US,0,US,M
2023,EN,FT,Data Engineer,65000,USD,65000,US,0,US,M
2023,SE,FT,Data Analyst,135000,USD,135000,US,0,US,M
2023,SE,FT,Data Analyst,105500,USD,105500,US,0,US,M
2023,SE,FT,Research Engineer,293000,USD,293000,US,0,US,M
2023,SE,FT,Research Engineer,185000,USD,185000,US,0,US,M
2023,SE,FT,Data Analyst,80000,USD,80000,US,0,US,M
2023,SE,FT,Data Analyst,70000,USD,70000,US,0,US,M
2023,SE,FT,Data Engineer,220000,USD,220000,US,100,US,M
2023,SE,FT,Data Engineer,160000,USD,160000,US,100,US,M
2023,SE,FT,Data Scientist,175000,USD,175000,US,100,US,M
2023,SE,FT,Data Scientist,145000,USD,145000,US,100,US,M
2023,SE,FT,Data Analyst,200000,USD,200000,US,0,US,M
2023,SE,FT,Data Analyst,148500,USD,148500,US,0,US,M
2023,SE,FT,Data Scientist,45000,EUR,48289,ES,0,ES,M
2023,SE,FT,Data Scientist,36000,EUR,38631,ES,0,ES,M
2023,SE,FT,Data Engineer,240500,USD,240500,US,0,US,L
2023,SE,FT,Data Engineer,123700,USD,123700,US,0,US,L
2023,SE,FT,Analytics Engineer,152900,USD,152900,US,100,US,M
2023,SE,FT,Analytics Engineer,117100,USD,117100,US,100,US,M
2023,SE,FT,Analytics Engineer,173000,USD,173000,US,100,US,M
2023,SE,FT,Analytics Engineer,113000,USD,113000,US,100,US,M
2023,SE,FT,Applied Scientist,260000,USD,260000,US,0,US,L
2023,SE,FT,Applied Scientist,136000,USD,136000,US,0,US,L
2023,EX,FT,Data Engineer,175000,USD,175000,US,0,US,M
2023,EX,FT,Data Engineer,110000,USD,110000,US,0,US,M
2023,SE,FT,Applied Scientist,260000,USD,260000,US,0,US,L
2023,SE,FT,Applied Scientist,136000,USD,136000,US,0,US,L
2023,SE,FT,Research Scientist,130000,USD,130000,US,100,US,M
2023,SE,FT,Research Scientist,110000,USD,110000,US,100,US,M
2023,SE,FT,Applied Scientist,205000,USD,205000,US,100,US,M
2023,SE,FT,Applied Scientist,184000,USD,184000,US,100,US,M
2023,SE,FT,Data Analyst,149500,USD,149500,US,100,US,M
2023,SE,FT,Data Analyst,127075,USD,127075,US,100,US,M
2023,SE,FT,Data Scientist,195000,USD,195000,US,0,US,M
2023,SE,FT,Data Scientist,160000,USD,160000,US,0,US,M
2023,SE,FT,Data Engineer,219535,USD,219535,US,100,US,M
2023,SE,FT,Data Engineer,146115,USD,146115,US,100,US,M
2023,SE,FT,Data Scientist,170000,USD,170000,US,0,US,M
2023,SE,FT,Data Scientist,135000,USD,135000,US,0,US,M
2023,SE,FT,Data Scientist,175000,USD,175000,US,100,US,M
2023,SE,FT,Data Scientist,145000,USD,145000,US,100,US,M
2023,SE,FT,Data Scientist,199000,USD,199000,US,0,US,M
2023,SE,FT,Data Scientist,162000,USD,162000,US,0,US,M
2023,SE,FT,Applied Scientist,222200,USD,222200,US,0,US,L
2023,SE,FT,Applied Scientist,136000,USD,136000,US,0,US,L
2023,EX,FT,Analytics Engineer,221000,USD,221000,US,100,US,M
2023,EX,FT,Analytics Engineer,153000,USD,153000,US,100,US,M
2023,SE,FT,Data Analyst,187000,USD,187000,US,0,US,M
2023,SE,FT,Data Analyst,128000,USD,128000,US,0,US,M
2023,SE,FT,Research Scientist,210000,USD,210000,US,0,US,M
2023,SE,FT,Research Scientist,136000,USD,136000,US,0,US,M
2023,SE,FT,Data Scientist,175000,USD,175000,US,100,US,M
2023,SE,FT,Data Scientist,100000,USD,100000,US,100,US,M
2023,SE,FT,Data Engineer,179000,USD,179000,US,0,US,M
2023,SE,FT,Data Engineer,109000,USD,109000,US,0,US,M
2023,SE,FT,Data Scientist,245000,USD,245000,US,0,US,M
2023,SE,FT,Data Scientist,180000,USD,180000,US,0,US,M
2023,SE,FT,Data Analyst,142000,USD,142000,US,100,US,M
2023,SE,FT,Data Analyst,75000,USD,75000,US,100,US,M
2023,SE,FT,Data Manager,198800,USD,198800,US,0,US,M
2023,SE,FT,Data Manager,105200,USD,105200,US,0,US,M
2023,SE,FT,Data Analyst,125000,USD,125000,US,100,US,M
2023,SE,FT,Data Analyst,112000,USD,112000,US,100,US,M
2023,SE,FT,Data Scientist,210000,USD,210000,US,0,US,M
2023,SE,FT,Data Scientist,155000,USD,155000,US,0,US,M
2023,SE,FT,Data Manager,115000,USD,115000,US,100,US,M
2023,SE,FT,Data Manager,86000,USD,86000,US,100,US,M
2023,SE,FT,Data Scientist,165000,USD,165000,US,0,US,M
2023,SE,FT,Data Scientist,140000,USD,140000,US,0,US,M
2023,SE,FT,Data Analyst,139000,USD,139000,US,0,US,M
2023,SE,FT,Data Analyst,106000,USD,106000,US,0,US,M
2023,EN,FT,Data Analyst,55000,CAD,40663,CA,0,CA,L
2022,SE,FT,AI Developer,275000,USD,275000,CA,0,CA,S
2023,SE,FL,Machine Learning Researcher,50000,USD,50000,UA,50,UA,S
2023,MI,FT,Machine Learning Engineer,280700,USD,280700,US,100,US,M
2023,MI,FT,Machine Learning Engineer,150450,USD,150450,US,100,US,M
2023,EN,FT,Data Scientist,70000,CAD,51753,CA,100,CA,L
2023,SE,FT,Data Architect,250500,USD,250500,US,0,US,M
2023,SE,FT,Data Architect,159500,USD,159500,US,0,US,M
2023,SE,FT,Data Engineer,145000,USD,145000,US,0,US,M
2023,SE,FT,Data Engineer,115000,USD,115000,US,0,US,M
2023,SE,FT,Data Analyst,140000,USD,140000,US,0,US,M
2023,SE,FT,Data Analyst,120000,USD,120000,US,0,US,M
2023,EN,FT,Data Scientist,130001,USD,130001,US,100,US,M
2023,EN,FT,Data Scientist,71907,USD,71907,US,100,US,M
2023,MI,FT,Data Scientist,93918,USD,93918,US,100,US,M
2023,MI,FT,Data Scientist,51962,USD,51962,US,100,US,M
2023,SE,FT,Data Analyst,175000,USD,175000,CA,100,CA,M
2023,SE,FT,Data Analyst,135000,USD,135000,CA,100,CA,M
2023,EN,FT,Data Engineer,85000,USD,85000,US,0,US,M
2023,EN,FT,Data Engineer,65000,USD,65000,US,0,US,M
2023,SE,FT,Machine Learning Engineer,257000,USD,257000,US,0,US,M
2023,SE,FT,Machine Learning Engineer,147000,USD,147000,US,0,US,M
2023,SE,FT,Data Engineer,222000,USD,222000,US,100,US,M
2023,SE,FT,Data Engineer,175000,USD,175000,US,100,US,M
2023,SE,FT,Data Scientist,203000,USD,203000,US,100,US,M
2023,SE,FT,Data Scientist,133200,USD,133200,US,100,US,M
2023,EN,FT,Applied Scientist,213660,USD,213660,US,0,US,L
2023,EN,FT,Applied Scientist,130760,USD,130760,US,0,US,L
2023,SE,FT,Data Engineer,221000,USD,221000,US,0,US,M
2023,SE,FT,Data Engineer,147000,USD,147000,US,0,US,M
2023,SE,FT,Data Quality Analyst,100000,USD,100000,US,0,US,M
2023,SE,FT,Data Quality Analyst,80000,USD,80000,US,0,US,M
2023,SE,FT,Data Scientist,185900,USD,185900,US,0,US,M

Now what exactly did I do?

First thing I did was to open the .csv file ```"ds_salaries.csv"```. I did this by calling the built-in Python function ```open()```

```py
open("ds_salaries.csv")
```

I wanted to open it in "read" mode, so there was no need of specifying the mode argument as it automatically defaults to this mode. However, you could include it if you wanted to be super clear.

```py
open("ds_salaries.csv", "r")
```

The ```open()``` function returns an object -- a file object to be precise. If you don't know what an object is, think of it as a data type just like a string, integer, float, boolean or list. So I stored this file object (or file datatype) in a variable which I named ```f```.

```py
f = open("ds_salaries.csv")
```

Remember, when you assign a function to a variable, whatever the function returns is what gets stored in the variable.

Objects have special functions called methods that work only on the object. For example:
* ```.split()``` is a string method (a special function that only works on string objects)
* ```.max``` is a list method (a special function that only works on list objects)

Likewise, the file object has methods. Examples are:
* ```.read()``` returns the data stored in the file as a text
* ```.close()``` closes the file.

Now, after opening the ```"ds_salaries.csv"``` file, and storing the file object in the variable ```f```, I called the ```.read()``` method to obtain all its data as a string. I then store this string in a variable ```file_data```.

```py
file_data = f.read()
```

Now, we can close the file to save up on resources.

```py
f.close()
```

I printed out the variable ```file_data``` just to ensure I have a string.

```py
print(file_data)
```

We can also check out the file data type with the ```type()``` function.

In [41]:
print(type(file_data))

<class 'str'>

Python provides another syntax for opening files, just in case you're like me and have the short attention span of a goldfish and you always forget to close the file. This special syntax auto-closes the file for you once you are done with it by using the ```with``` keyword and code indentation. Let's see how it works in code.

In [42]:
with open("ds_salaries.csv") as f:
    data = f.read()

print(data)

work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
2023,SE,FT,Principal Data Scientist,80000,EUR,85847,ES,100,ES,L
2023,MI,CT,ML Engineer,30000,USD,30000,US,100,US,S
2023,MI,CT,ML Engineer,25500,USD,25500,US,100,US,S
2023,SE,FT,Data Scientist,175000,USD,175000,CA,100,CA,M
2023,SE,FT,Data Scientist,120000,USD,120000,CA,100,CA,M
2023,SE,FT,Applied Scientist,222200,USD,222200,US,0,US,L
2023,SE,FT,Applied Scientist,136000,USD,136000,US,0,US,L
2023,SE,FT,Data Scientist,219000,USD,219000,CA,0,CA,M
2023,SE,FT,Data Scientist,141000,USD,141000,CA,0,CA,M
2023,SE,FT,Data Scientist,147100,USD,147100,US,0,US,M
2023,SE,FT,Data Scientist,90700,USD,90700,US,0,US,M
2023,SE,FT,Data Analyst,130000,USD,130000,US,100,US,M
2023,SE,FT,Data Analyst,100000,USD,100000,US,100,US,M
2023,EN,FT,Applied Scientist,213660,USD,213660,US,0,US,L
2023,EN,FT,Applied Scientist,130760,USD,130760,US,0,US,L
2023,SE,FT,Data Modeler,147100,USD,147100,US,0,US,M
2023,SE,FT,Data Modeler,90700,USD,90700,US,0,US,M
2023,SE,FT,Data Scientist,170000,USD,170000,US,0,US,M
2023,SE,FT,Data Scientist,150000,USD,150000,US,0,US,M
2023,MI,FT,Data Analyst,150000,USD,150000,US,100,US,M
2023,MI,FT,Data Analyst,110000,USD,110000,US,100,US,M
2023,SE,FT,Research Engineer,275000,USD,275000,DE,0,DE,M
2023,SE,FT,Research Engineer,174000,USD,174000,DE,0,DE,M
2023,SE,FT,Analytics Engineer,230000,USD,230000,GB,100,GB,M
2023,SE,FT,Analytics Engineer,143200,USD,143200,GB,100,GB,M
2023,SE,FT,Business Intelligence Engineer,225000,USD,225000,US,0,US,M
2023,SE,FT,Business Intelligence Engineer,156400,USD,156400,US,0,US,M
2023,SE,FT,Machine Learning Engineer,200000,USD,200000,US,0,US,M
2023,SE,FT,Machine Learning Engineer,130000,USD,130000,US,0,US,M
2023,SE,FT,Data Strategist,90000,USD,90000,CA,0,CA,M
2023,SE,FT,Data Strategist,72000,USD,72000,CA,0,CA,M
2023,SE,FT,Data Engineer,253200,USD,253200,US,0,US,M
2023,SE,FT,Data Engineer,90700,USD,90700,US,0,US,M
2023,SE,FT,Computer Vision Engineer,342810,USD,342810,US,0,US,M
2023,SE,FT,Computer Vision Engineer,184590,USD,184590,US,0,US,M
2023,MI,FT,Data Engineer,162500,USD,162500,US,0,US,M
2023,MI,FT,Data Engineer,130000,USD,130000,US,0,US,M
2023,MI,FT,Data Analyst,105380,USD,105380,US,0,US,M
2023,MI,FT,Data Analyst,64500,USD,64500,US,0,US,M
2023,EN,FT,Data Quality Analyst,100000,USD,100000,NG,100,NG,L
2023,EN,FT,Compliance Data Analyst,30000,USD,30000,NG,100,NG,L
2022,MI,FT,Machine Learning Engineer,1650000,INR,20984,IN,50,IN,L
2023,EN,FT,Applied Scientist,204620,USD,204620,US,0,US,L
2023,EN,FT,Applied Scientist,110680,USD,110680,US,0,US,L
2023,SE,FT,Data Engineer,270703,USD,270703,US,0,US,M
2023,SE,FT,Data Engineer,221484,USD,221484,US,0,US,M
2023,SE,FT,Data Scientist,212750,USD,212750,US,100,US,M
2023,SE,FT,Data Scientist,185000,USD,185000,US,100,US,M
2023,SE,FT,Data Scientist,262000,USD,262000,US,100,US,M
2023,SE,FT,Data Scientist,245000,USD,245000,US,100,US,M
2023,SE,FT,Data Scientist,275300,USD,275300,US,100,US,M
2023,SE,FT,Data Scientist,183500,USD,183500,US,100,US,M
2023,SE,FT,Data Scientist,218500,USD,218500,US,100,US,M
2023,SE,FT,Data Scientist,199098,USD,199098,US,100,US,M
2023,SE,FT,Data Engineer,203300,USD,203300,US,100,US,M
2023,SE,FT,Data Engineer,123600,USD,123600,US,100,US,M
2023,SE,FT,Research Engineer,189110,USD,189110,US,0,US,M
2023,SE,FT,Research Engineer,139000,USD,139000,US,0,US,M
2023,EX,FT,Data Scientist,258750,USD,258750,US,0,US,M
2023,EX,FT,Data Scientist,185000,USD,185000,US,0,US,M
2023,SE,FT,Data Engineer,231500,USD,231500,US,100,US,M
2023,SE,FT,Data Engineer,166000,USD,166000,US,100,US,M
2023,SE,FT,Data Scientist,172500,USD,172500,US,100,US,M
2023,SE,FT,Data Scientist,110500,USD,110500,US,100,US,M
2023,SE,FT,Data Engineer,238000,USD,238000,US,0,US,M
2023,SE,FT,Data Engineer,176000,USD,176000,US,0,US,M
2023,SE,FT,Data Engineer,237000,USD,237000,US,100,US,M
2023,SE,FT,Data Engineer,201450,USD,201450,US,100,US,M
2023,SE,FT,Applied Scientist,309400,USD,309400,US,0,US,L
2023,SE,FT,Applied Scientist,159100,USD,159100,US,0,US,L
2023,SE,FT,Data Engineer,115000,USD,115000,US,0,US,M
2023,SE,FT,Data Engineer,81500,USD,81500,US,0,US,M
2023,SE,FT,Data Scientist,237000,USD,237000,US,100,US,M
2023,SE,FT,Data Scientist,201450,USD,201450,US,100,US,M
2023,SE,FT,Computer Vision Engineer,280000,USD,280000,US,0,US,M
2023,SE,FT,Computer Vision Engineer,210000,USD,210000,US,0,US,M
2023,SE,FT,Data Architect,280100,USD,280100,US,100,US,M
2023,SE,FT,Data Architect,168100,USD,168100,US,100,US,M
2023,SE,FT,Data Engineer,193500,USD,193500,US,100,US,M
2023,SE,FT,Data Engineer,139000,USD,139000,US,100,US,M
2023,MI,FT,Data Scientist,510000,HKD,65062,HK,0,HK,L
2023,SE,FT,Machine Learning Engineer,150000,USD,150000,PT,100,US,M
2023,MI,FT,Applied Machine Learning Engineer,65000,EUR,69751,IN,100,DE,S
2022,EN,FT,AI Developer,300000,USD,300000,IN,50,IN,L
2023,MI,FT,Machine Learning Engineer,90000,EUR,96578,NL,100,NL,L
2023,SE,FT,Business Intelligence Engineer,185900,USD,185900,US,0,US,M
2023,SE,FT,Business Intelligence Engineer,129300,USD,129300,US,0,US,M
2023,SE,FT,Data Engineer,225000,USD,225000,US,100,US,M
2023,SE,FT,Data Engineer,175000,USD,175000,US,100,US,M
2023,SE,FT,Data Engineer,185000,USD,185000,US,0,US,M
2023,SE,FT,Data Engineer,140000,USD,140000,US,0,US,M
2023,SE,FT,Data Scientist,45000,EUR,48289,ES,0,ES,M
2023,SE,FT,Data Scientist,36000,EUR,38631,ES,0,ES,M
2023,SE,FT,Data Scientist,105000,USD,105000,US,0,US,M
2023,SE,FT,Data Scientist,70000,USD,70000,US,0,US,M
2023,EN,FT,Machine Learning Engineer,163196,USD,163196,US,0,US,M
2023,EN,FT,Machine Learning Engineer,145885,USD,145885,US,0,US,M
2023,SE,FT,Data Engineer,217000,USD,217000,US,100,US,M
2023,SE,FT,Data Engineer,185000,USD,185000,US,100,US,M
2023,SE,FT,Data Analyst,202800,USD,202800,US,0,US,L
2023,SE,FT,Data Analyst,104300,USD,104300,US,0,US,L
2023,SE,FT,Data Analyst,145000,USD,145000,US,0,US,M
2023,SE,FT,Data Analyst,65000,USD,65000,US,0,US,M
2023,SE,FT,Data Engineer,165000,USD,165000,US,0,US,M
2023,SE,FT,Data Engineer,132300,USD,132300,US,0,US,M
2023,SE,FT,Data Engineer,179170,USD,179170,US,0,US,M
2023,SE,FT,Data Engineer,94300,USD,94300,US,0,US,M
2023,SE,FT,Analytics Engineer,152500,USD,152500,US,0,US,M
2023,SE,FT,Analytics Engineer,116450,USD,116450,US,0,US,M
2023,SE,FT,Data Engineer,247300,USD,247300,US,0,US,M
2023,SE,FT,Data Engineer,133800,USD,133800,US,0,US,M
2023,SE,FT,Research Engineer,203000,USD,203000,US,0,US,M
2023,SE,FT,Research Engineer,133000,USD,133000,US,0,US,M
2023,EN,FT,Research Scientist,220000,USD,220000,US,50,US,L
2022,EN,FT,Machine Learning Engineer,54000,CHF,56536,CH,100,CH,S
2023,SE,FT,Data Scientist,150000,USD,150000,US,0,US,M
2023,SE,FT,Data Scientist,120000,USD,120000,US,0,US,M
2023,SE,FT,Analytics Engineer,289800,USD,289800,US,0,US,M
2023,SE,FT,Analytics Engineer,214000,USD,214000,US,0,US,M
2023,SE,FT,Analytics Engineer,179820,USD,179820,US,0,US,M
2023,SE,FT,Analytics Engineer,143860,USD,143860,US,0,US,M
2023,SE,FT,Machine Learning Engineer,283200,USD,283200,US,100,US,M
2023,SE,FT,Machine Learning Engineer,188800,USD,188800,US,100,US,M
2023,SE,FT,Analytics Engineer,289800,USD,289800,US,0,US,M
2023,SE,FT,Analytics Engineer,214200,USD,214200,US,0,US,M
2023,SE,FT,Data Engineer,185900,USD,185900,US,0,US,M
2023,SE,FT,Data Engineer,129300,USD,129300,US,0,US,M
2023,SE,FT,Data Engineer,252000,USD,252000,US,0,US,M
2023,SE,FT,Data Engineer,129000,USD,129000,US,0,US,M
2023,MI,FT,Data Analytics Manager,155000,USD,155000,US,0,US,M
2023,MI,FT,Data Analytics Manager,140000,USD,140000,US,0,US,M
2023,SE,FT,Data Engineer,161800,USD,161800,US,100,US,M
2023,SE,FT,Data Engineer,141600,USD,141600,US,100,US,M
2023,SE,FT,Machine Learning Engineer,342300,USD,342300,US,0,US,L
2023,SE,FT,Machine Learning Engineer,176100,USD,176100,US,0,US,L
2023,MI,FT,Data Engineer,100000,USD,100000,US,100,US,M
2023,MI,FT,Data Engineer,70000,USD,70000,US,100,US,M
2023,EN,FT,Data Engineer,85000,USD,85000,US,0,US,M
2023,EN,FT,Data Engineer,65000,USD,65000,US,0,US,M
2023,SE,FT,Data Scientist,138784,USD,138784,US,100,US,M
2023,SE,FT,Data Scientist,83270,USD,83270,US,100,US,M
2023,EN,FT,Data Analyst,75000,USD,75000,US,0,US,M
2023,EN,FT,Data Analyst,70000,USD,70000,US,0,US,M
2023,SE,FT,Data Analyst,204500,USD,204500,US,0,US,M
2023,SE,FT,Data Analyst,138900,USD,138900,US,0,US,M
2023,SE,FT,Machine Learning Engineer,318300,USD,318300,US,100,US,M
2023,SE,FT,Machine Learning Engineer,212200,USD,212200,US,100,US,M
2023,SE,FT,Data Engineer,95000,USD,95000,US,100,US,M
2023,SE,FT,Data Engineer,75000,USD,75000,US,100,US,M
2023,SE,FT,Data Scientist,195000,USD,195000,US,0,US,M
2023,SE,FT,Data Scientist,160000,USD,160000,US,0,US,M
2023,SE,FT,Analytics Engineer,230000,USD,230000,US,0,US,M
2023,SE,FT,Analytics Engineer,143200,USD,143200,US,0,US,M
2023,MI,FT,Data Engineer,100000,USD,100000,US,100,US,M
2023,MI,FT,Data Engineer,70000,USD,70000,US,100,US,M
2023,MI,FT,Business Data Analyst,105000,USD,105000,US,50,US,L
2023,MI,FT,Applied Data Scientist,1700000,INR,20670,IN,100,IN,L
2023,MI,FT,Data Analyst,38000,GBP,46178,GB,0,GB,M
2023,MI,FT,Data Analyst,35000,GBP,42533,GB,0,GB,M
2023,SE,FT,Data Engineer,145000,USD,145000,US,0,US,M
2023,SE,FT,Data Engineer,115000,USD,115000,US,0,US,M
2023,SE,FT,Data Analyst,168400,USD,168400,US,0,US,M
2023,SE,FT,Data Analyst,105200,USD,105200,US,0,US,M
2023,SE,FT,Applied Scientist,309400,USD,309400,US,0,US,L
2023,SE,FT,Applied Scientist,159100,USD,159100,US,0,US,L
2023,SE,FT,Machine Learning Engineer,190000,USD,190000,US,0,US,M
2023,SE,FT,Machine Learning Engineer,150000,USD,150000,US,0,US,M
2023,MI,FT,Data Engineer,162500,USD,162500,US,0,US,M
2023,MI,FT,Data Engineer,130000,USD,130000,US,0,US,M
2023,SE,FT,Analytics Engineer,150000,USD,150000,US,100,US,M
2023,SE,FT,Analytics Engineer,120000,USD,120000,US,100,US,M
2023,SE,FT,Data Engineer,145000,USD,145000,US,0,US,M
2023,SE,FT,Data Engineer,120000,USD,120000,US,0,US,M
2023,SE,FT,Applied Scientist,222200,USD,222200,US,0,US,L
2023,SE,FT,Applied Scientist,136000,USD,136000,US,0,US,L
2023,SE,FT,Data Analyst,45000,GBP,54685,CF,100,CF,M
2023,SE,FT,Data Analyst,35000,GBP,42533,CF,100,CF,M
2023,SE,FT,Data Engineer,241000,USD,241000,US,0,US,M
2023,SE,FT,Data Engineer,155000,USD,155000,US,0,US,M
2023,SE,FT,Data Engineer,220000,USD,220000,US,100,US,M
2023,SE,FT,Data Engineer,190000,USD,190000,US,100,US,M
2023,MI,FT,Data Scientist,55000,GBP,66837,GB,0,GB,M
2023,MI,FT,Data Scientist,45000,GBP,54685,GB,0,GB,M
2020,EX,FT,Staff Data Analyst,15000,USD,15000,NG,0,CA,M
2023,MI,FT,ETL Engineer,70000,GBP,85066,GB,100,GB,M
2023,MI,FT,ETL Engineer,47500,GBP,57723,GB,100,GB,M
2023,EN,FT,Data Analyst,85000,USD,85000,US,100,US,M
2023,EN,FT,Data Analyst,75000,USD,75000,US,100,US,M
2023,SE,FT,Data Engineer,160000,USD,160000,US,0,US,M
2023,SE,FT,Data Engineer,140000,USD,140000,US,0,US,M
2023,MI,FT,Machine Learning Engineer,300000,USD,300000,US,0,US,M
2023,MI,FT,Machine Learning Engineer,250000,USD,250000,US,0,US,M
2023,SE,FT,Data Scientist,228000,USD,228000,US,0,US,M
2023,SE,FT,Data Scientist,186000,USD,186000,US,0,US,M
2023,SE,FT,Data Scientist,190000,USD,190000,US,0,US,M
2023,SE,FT,Data Scientist,170000,USD,170000,US,0,US,M
2023,MI,FT,Research Engineer,230000,USD,230000,US,0,US,M
2023,MI,FT,Research Engineer,200000,USD,200000,US,0,US,M
2023,SE,FT,Data Architect,180000,USD,180000,US,100,US,M
2023,SE,FT,Data Architect,115000,USD,115000,US,100,US,M
2023,SE,FT,Data Architect,200000,USD,200000,US,100,US,M
2023,SE,FT,Data Architect,115000,USD,115000,US,100,US,M
2023,SE,FT,Data DevOps Engineer,50000,EUR,53654,FR,50,FR,S
2023,EX,FT,Data Engineer,220000,USD,220000,US,0,US,M
2023,EX,FT,Data Engineer,205000,USD,205000,US,0,US,M
2023,MI,FT,Data Engineer,180000,USD,180000,US,0,US,M
2023,MI,FT,Data Engineer,130000,USD,130000,US,0,US,M
2023,SE,FT,Data Engineer,200000,USD,200000,US,100,US,M
2023,SE,FT,Data Engineer,150000,USD,150000,US,100,US,M
2023,SE,FT,Computer Vision Engineer,215000,USD,215000,US,0,US,M
2023,SE,FT,Computer Vision Engineer,170000,USD,170000,US,0,US,M
2023,SE,FT,Machine Learning Engineer,247500,USD,247500,US,0,US,M
2023,SE,FT,Machine Learning Engineer,172200,USD,172200,US,0,US,M
2023,SE,FT,Data Scientist,224000,USD,224000,CA,0,CA,M
2023,SE,FT,Data Scientist,176000,USD,176000,CA,0,CA,M
2023,SE,FT,Data Analyst,120000,USD,120000,US,100,US,M
2023,SE,FT,Data Analyst,75000,USD,75000,US,100,US,M
2023,EN,FT,Data Engineer,1400000,INR,17022,IN,100,IN,L
2023,SE,FT,Applied Data Scientist,100000,AUD,68318,AU,100,FI,M
2023,MI,FT,AI Developer,100000,SGD,75020,FI,0,FI,M
2023,SE,FT,Data Analyst,140000,USD,140000,US,0,US,M
2023,SE,FT,Data Analyst,120000,USD,120000,US,0,US,M
2023,SE,FT,Data Engineer,128000,USD,128000,US,0,US,M
2023,SE,FT,Data Engineer,81500,USD,81500,US,0,US,M
2023,SE,FT,Data Engineer,145000,USD,145000,US,0,US,M
2023,SE,FT,Data Engineer,115000,USD,115000,US,0,US,M
2023,SE,FT,Data Engineer,185000,USD,185000,US,0,US,M
2023,SE,FT,Data Engineer,140000,USD,140000,US,0,US,M
2023,EX,FT,Head of Data,329500,USD,329500,US,0,US,M
2023,EX,FT,Head of Data,269600,USD,269600,US,0,US,M
2023,SE,FT,Data Quality Analyst,100000,USD,100000,US,0,US,M
2023,SE,FT,Data Quality Analyst,80000,USD,80000,US,0,US,M
2023,SE,FT,Data Scientist,250000,USD,250000,US,0,US,M
2023,SE,FT,Data Scientist,162500,USD,162500,US,0,US,M
2023,MI,FT,AI Developer,200000,USD,200000,US,100,US,M
2023,SE,FT,Data Engineer,145000,USD,145000,US,0,US,M
2023,SE,FT,Data Engineer,100000,USD,100000,US,0,US,M
2023,EX,FT,Data Engineer,145000,USD,145000,US,0,US,M
2023,EX,FT,Data Engineer,115000,USD,115000,US,0,US,M
2023,SE,FT,Data Scientist,203500,USD,203500,US,0,US,M
2023,SE,FT,Data Scientist,152000,USD,152000,US,0,US,M
2023,SE,FT,Data Scientist,239000,USD,239000,US,0,US,L
2023,SE,FT,Data Scientist,122900,USD,122900,US,0,US,L
2023,SE,FT,Data Scientist,237000,USD,237000,US,0,US,M
2023,SE,FT,Data Scientist,145000,USD,145000,US,0,US,M
2023,SE,FT,Data Science Manager,191765,USD,191765,US,0,US,M
2023,SE,FT,Data Science Manager,134236,USD,134236,US,0,US,M
2023,SE,FT,Analytics Engineer,190000,USD,190000,US,100,US,M
2023,SE,FT,Analytics Engineer,112000,USD,112000,US,100,US,M
2022,SE,FT,Data Scientist,84000,EUR,88256,ES,100,GB,L
2023,EN,FT,Data Engineer,85000,USD,85000,US,0,US,M
2023,EN,FT,Data Engineer,65000,USD,65000,US,0,US,M
2023,SE,FT,Data Analyst,135000,USD,135000,US,0,US,M
2023,SE,FT,Data Analyst,105500,USD,105500,US,0,US,M
2023,SE,FT,Research Engineer,293000,USD,293000,US,0,US,M
2023,SE,FT,Research Engineer,185000,USD,185000,US,0,US,M
2023,SE,FT,Data Analyst,80000,USD,80000,US,0,US,M
2023,SE,FT,Data Analyst,70000,USD,70000,US,0,US,M
2023,SE,FT,Data Engineer,220000,USD,220000,US,100,US,M
2023,SE,FT,Data Engineer,160000,USD,160000,US,100,US,M
2023,SE,FT,Data Scientist,175000,USD,175000,US,100,US,M
2023,SE,FT,Data Scientist,145000,USD,145000,US,100,US,M
2023,SE,FT,Data Analyst,200000,USD,200000,US,0,US,M
2023,SE,FT,Data Analyst,148500,USD,148500,US,0,US,M
2023,SE,FT,Data Scientist,45000,EUR,48289,ES,0,ES,M
2023,SE,FT,Data Scientist,36000,EUR,38631,ES,0,ES,M
2023,SE,FT,Data Engineer,240500,USD,240500,US,0,US,L
2023,SE,FT,Data Engineer,123700,USD,123700,US,0,US,L
2023,SE,FT,Analytics Engineer,152900,USD,152900,US,100,US,M
2023,SE,FT,Analytics Engineer,117100,USD,117100,US,100,US,M
2023,SE,FT,Analytics Engineer,173000,USD,173000,US,100,US,M
2023,SE,FT,Analytics Engineer,113000,USD,113000,US,100,US,M
2023,SE,FT,Applied Scientist,260000,USD,260000,US,0,US,L
2023,SE,FT,Applied Scientist,136000,USD,136000,US,0,US,L
2023,EX,FT,Data Engineer,175000,USD,175000,US,0,US,M
2023,EX,FT,Data Engineer,110000,USD,110000,US,0,US,M
2023,SE,FT,Applied Scientist,260000,USD,260000,US,0,US,L
2023,SE,FT,Applied Scientist,136000,USD,136000,US,0,US,L
2023,SE,FT,Research Scientist,130000,USD,130000,US,100,US,M
2023,SE,FT,Research Scientist,110000,USD,110000,US,100,US,M
2023,SE,FT,Applied Scientist,205000,USD,205000,US,100,US,M
2023,SE,FT,Applied Scientist,184000,USD,184000,US,100,US,M
2023,SE,FT,Data Analyst,149500,USD,149500,US,100,US,M
2023,SE,FT,Data Analyst,127075,USD,127075,US,100,US,M
2023,SE,FT,Data Scientist,195000,USD,195000,US,0,US,M
2023,SE,FT,Data Scientist,160000,USD,160000,US,0,US,M
2023,SE,FT,Data Engineer,219535,USD,219535,US,100,US,M
2023,SE,FT,Data Engineer,146115,USD,146115,US,100,US,M
2023,SE,FT,Data Scientist,170000,USD,170000,US,0,US,M
2023,SE,FT,Data Scientist,135000,USD,135000,US,0,US,M
2023,SE,FT,Data Scientist,175000,USD,175000,US,100,US,M
2023,SE,FT,Data Scientist,145000,USD,145000,US,100,US,M
2023,SE,FT,Data Scientist,199000,USD,199000,US,0,US,M
2023,SE,FT,Data Scientist,162000,USD,162000,US,0,US,M
2023,SE,FT,Applied Scientist,222200,USD,222200,US,0,US,L
2023,SE,FT,Applied Scientist,136000,USD,136000,US,0,US,L
2023,EX,FT,Analytics Engineer,221000,USD,221000,US,100,US,M
2023,EX,FT,Analytics Engineer,153000,USD,153000,US,100,US,M
2023,SE,FT,Data Analyst,187000,USD,187000,US,0,US,M
2023,SE,FT,Data Analyst,128000,USD,128000,US,0,US,M
2023,SE,FT,Research Scientist,210000,USD,210000,US,0,US,M
2023,SE,FT,Research Scientist,136000,USD,136000,US,0,US,M
2023,SE,FT,Data Scientist,175000,USD,175000,US,100,US,M
2023,SE,FT,Data Scientist,100000,USD,100000,US,100,US,M
2023,SE,FT,Data Engineer,179000,USD,179000,US,0,US,M
2023,SE,FT,Data Engineer,109000,USD,109000,US,0,US,M
2023,SE,FT,Data Scientist,245000,USD,245000,US,0,US,M
2023,SE,FT,Data Scientist,180000,USD,180000,US,0,US,M
2023,SE,FT,Data Analyst,142000,USD,142000,US,100,US,M
2023,SE,FT,Data Analyst,75000,USD,75000,US,100,US,M
2023,SE,FT,Data Manager,198800,USD,198800,US,0,US,M
2023,SE,FT,Data Manager,105200,USD,105200,US,0,US,M
2023,SE,FT,Data Analyst,125000,USD,125000,US,100,US,M
2023,SE,FT,Data Analyst,112000,USD,112000,US,100,US,M
2023,SE,FT,Data Scientist,210000,USD,210000,US,0,US,M
2023,SE,FT,Data Scientist,155000,USD,155000,US,0,US,M
2023,SE,FT,Data Manager,115000,USD,115000,US,100,US,M
2023,SE,FT,Data Manager,86000,USD,86000,US,100,US,M
2023,SE,FT,Data Scientist,165000,USD,165000,US,0,US,M
2023,SE,FT,Data Scientist,140000,USD,140000,US,0,US,M
2023,SE,FT,Data Analyst,139000,USD,139000,US,0,US,M
2023,SE,FT,Data Analyst,106000,USD,106000,US,0,US,M
2023,EN,FT,Data Analyst,55000,CAD,40663,CA,0,CA,L
2022,SE,FT,AI Developer,275000,USD,275000,CA,0,CA,S
2023,SE,FL,Machine Learning Researcher,50000,USD,50000,UA,50,UA,S
2023,MI,FT,Machine Learning Engineer,280700,USD,280700,US,100,US,M
2023,MI,FT,Machine Learning Engineer,150450,USD,150450,US,100,US,M
2023,EN,FT,Data Scientist,70000,CAD,51753,CA,100,CA,L
2023,SE,FT,Data Architect,250500,USD,250500,US,0,US,M
2023,SE,FT,Data Architect,159500,USD,159500,US,0,US,M
2023,SE,FT,Data Engineer,145000,USD,145000,US,0,US,M
2023,SE,FT,Data Engineer,115000,USD,115000,US,0,US,M
2023,SE,FT,Data Analyst,140000,USD,140000,US,0,US,M
2023,SE,FT,Data Analyst,120000,USD,120000,US,0,US,M
2023,EN,FT,Data Scientist,130001,USD,130001,US,100,US,M
2023,EN,FT,Data Scientist,71907,USD,71907,US,100,US,M
2023,MI,FT,Data Scientist,93918,USD,93918,US,100,US,M
2023,MI,FT,Data Scientist,51962,USD,51962,US,100,US,M
2023,SE,FT,Data Analyst,175000,USD,175000,CA,100,CA,M
2023,SE,FT,Data Analyst,135000,USD,135000,CA,100,CA,M
2023,EN,FT,Data Engineer,85000,USD,85000,US,0,US,M
2023,EN,FT,Data Engineer,65000,USD,65000,US,0,US,M
2023,SE,FT,Machine Learning Engineer,257000,USD,257000,US,0,US,M
2023,SE,FT,Machine Learning Engineer,147000,USD,147000,US,0,US,M
2023,SE,FT,Data Engineer,222000,USD,222000,US,100,US,M
2023,SE,FT,Data Engineer,175000,USD,175000,US,100,US,M
2023,SE,FT,Data Scientist,203000,USD,203000,US,100,US,M
2023,SE,FT,Data Scientist,133200,USD,133200,US,100,US,M
2023,EN,FT,Applied Scientist,213660,USD,213660,US,0,US,L
2023,EN,FT,Applied Scientist,130760,USD,130760,US,0,US,L
2023,SE,FT,Data Engineer,221000,USD,221000,US,0,US,M
2023,SE,FT,Data Engineer,147000,USD,147000,US,0,US,M
2023,SE,FT,Data Quality Analyst,100000,USD,100000,US,0,US,M
2023,SE,FT,Data Quality Analyst,80000,USD,80000,US,0,US,M
2023,SE,FT,Data Scientist,185900,USD,185900,US,0,US,M

Bingo! Same results! All this does is call the ```open()``` function and assigns the file object to a variable ```f```. We can now reference the file object ```f``` while within the ```with``` code block. Once outside the code block, the file is automatically closed. Pretty neat, huh?

Ok, that's cool. But what now? We have the data as a single long string which is not really exciting in the field of data analysis. Well, we can turn it into a list...

In [43]:
salaries = data.split(',')
print(salaries)

['work_year', 'experience_level', 'employment_type', 'job_title', 'salary', 'salary_currency', 'salary_in_usd', 'employee_residence', 'remote_ratio', 'company_location', 'company_size\n2023', 'SE', 'FT', 'Principal Data Scientist', '80000', 'EUR', '85847', 'ES', '100', 'ES', 'L\n2023', 'MI', 'CT', 'ML Engineer', '30000', 'USD', '30000', 'US', '100', 'US', 'S\n2023', 'MI', 'CT', 'ML Engineer', '25500', 'USD', '25500', 'US', '100', 'US', 'S\n2023', 'SE', 'FT', 'Data Scientist', '175000', 'USD', '175000', 'CA', '100', 'CA', 'M\n2023', 'SE', 'FT', 'Data Scientist', '120000', 'USD', '120000', 'CA', '100', 'CA', 'M\n2023', 'SE', 'FT', 'Applied Scientist', '222200', 'USD', '222200', 'US', '0', 'US', 'L\n2023', 'SE', 'FT', 'Applied Scientist', '136000', 'USD', '136000', 'US', '0', 'US', 'L\n2023', 'SE', 'FT', 'Data Scientist', '219000', 'USD', '219000', 'CA', '0', 'CA', 'M\n2023', 'SE', 'FT', 'Data Scientist', '141000', 'USD', '141000', 'CA', '0', 'CA', 'M\n2023', 'SE', 'FT', 'Data Scientist', '147100', 'USD', '147100', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '90700', 'USD', '90700', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Analyst', '130000', 'USD', '130000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Analyst', '100000', 'USD', '100000', 'US', '100', 'US', 'M\n2023', 'EN', 'FT', 'Applied Scientist', '213660', 'USD', '213660', 'US', '0', 'US', 'L\n2023', 'EN', 'FT', 'Applied Scientist', '130760', 'USD', '130760', 'US', '0', 'US', 'L\n2023', 'SE', 'FT', 'Data Modeler', '147100', 'USD', '147100', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Modeler', '90700', 'USD', '90700', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '170000', 'USD', '170000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '150000', 'USD', '150000', 'US', '0', 'US', 'M\n2023', 'MI', 'FT', 'Data Analyst', '150000', 'USD', '150000', 'US', '100', 'US', 'M\n2023', 'MI', 'FT', 'Data Analyst', '110000', 'USD', '110000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Research Engineer', '275000', 'USD', '275000', 'DE', '0', 'DE', 'M\n2023', 'SE', 'FT', 'Research Engineer', '174000', 'USD', '174000', 'DE', '0', 'DE', 'M\n2023', 'SE', 'FT', 'Analytics Engineer', '230000', 'USD', '230000', 'GB', '100', 'GB', 'M\n2023', 'SE', 'FT', 'Analytics Engineer', '143200', 'USD', '143200', 'GB', '100', 'GB', 'M\n2023', 'SE', 'FT', 'Business Intelligence Engineer', '225000', 'USD', '225000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Business Intelligence Engineer', '156400', 'USD', '156400', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Machine Learning Engineer', '200000', 'USD', '200000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Machine Learning Engineer', '130000', 'USD', '130000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Strategist', '90000', 'USD', '90000', 'CA', '0', 'CA', 'M\n2023', 'SE', 'FT', 'Data Strategist', '72000', 'USD', '72000', 'CA', '0', 'CA', 'M\n2023', 'SE', 'FT', 'Data Engineer', '253200', 'USD', '253200', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '90700', 'USD', '90700', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Computer Vision Engineer', '342810', 'USD', '342810', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Computer Vision Engineer', '184590', 'USD', '184590', 'US', '0', 'US', 'M\n2023', 'MI', 'FT', 'Data Engineer', '162500', 'USD', '162500', 'US', '0', 'US', 'M\n2023', 'MI', 'FT', 'Data Engineer', '130000', 'USD', '130000', 'US', '0', 'US', 'M\n2023', 'MI', 'FT', 'Data Analyst', '105380', 'USD', '105380', 'US', '0', 'US', 'M\n2023', 'MI', 'FT', 'Data Analyst', '64500', 'USD', '64500', 'US', '0', 'US', 'M\n2023', 'EN', 'FT', 'Data Quality Analyst', '100000', 'USD', '100000', 'NG', '100', 'NG', 'L\n2023', 'EN', 'FT', 'Compliance Data Analyst', '30000', 'USD', '30000', 'NG', '100', 'NG', 'L\n2022', 'MI', 'FT', 'Machine Learning Engineer', '1650000', 'INR', '20984', 'IN', '50', 'IN', 'L\n2023', 'EN', 'FT', 'Applied Scientist', '204620', 'USD', '204620', 'US', '0', 'US', 'L\n2023', 'EN', 'FT', 'Applied Scientist', '110680', 'USD', '110680', 'US', '0', 'US', 'L\n2023', 'SE', 'FT', 'Data Engineer', '270703', 'USD', '270703', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '221484', 'USD', '221484', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '212750', 'USD', '212750', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '185000', 'USD', '185000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '262000', 'USD', '262000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '245000', 'USD', '245000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '275300', 'USD', '275300', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '183500', 'USD', '183500', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '218500', 'USD', '218500', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '199098', 'USD', '199098', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '203300', 'USD', '203300', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '123600', 'USD', '123600', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Research Engineer', '189110', 'USD', '189110', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Research Engineer', '139000', 'USD', '139000', 'US', '0', 'US', 'M\n2023', 'EX', 'FT', 'Data Scientist', '258750', 'USD', '258750', 'US', '0', 'US', 'M\n2023', 'EX', 'FT', 'Data Scientist', '185000', 'USD', '185000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '231500', 'USD', '231500', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '166000', 'USD', '166000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '172500', 'USD', '172500', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '110500', 'USD', '110500', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '238000', 'USD', '238000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '176000', 'USD', '176000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '237000', 'USD', '237000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '201450', 'USD', '201450', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Applied Scientist', '309400', 'USD', '309400', 'US', '0', 'US', 'L\n2023', 'SE', 'FT', 'Applied Scientist', '159100', 'USD', '159100', 'US', '0', 'US', 'L\n2023', 'SE', 'FT', 'Data Engineer', '115000', 'USD', '115000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '81500', 'USD', '81500', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '237000', 'USD', '237000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '201450', 'USD', '201450', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Computer Vision Engineer', '280000', 'USD', '280000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Computer Vision Engineer', '210000', 'USD', '210000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Architect', '280100', 'USD', '280100', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Architect', '168100', 'USD', '168100', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '193500', 'USD', '193500', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '139000', 'USD', '139000', 'US', '100', 'US', 'M\n2023', 'MI', 'FT', 'Data Scientist', '510000', 'HKD', '65062', 'HK', '0', 'HK', 'L\n2023', 'SE', 'FT', 'Machine Learning Engineer', '150000', 'USD', '150000', 'PT', '100', 'US', 'M\n2023', 'MI', 'FT', 'Applied Machine Learning Engineer', '65000', 'EUR', '69751', 'IN', '100', 'DE', 'S\n2022', 'EN', 'FT', 'AI Developer', '300000', 'USD', '300000', 'IN', '50', 'IN', 'L\n2023', 'MI', 'FT', 'Machine Learning Engineer', '90000', 'EUR', '96578', 'NL', '100', 'NL', 'L\n2023', 'SE', 'FT', 'Business Intelligence Engineer', '185900', 'USD', '185900', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Business Intelligence Engineer', '129300', 'USD', '129300', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '225000', 'USD', '225000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '175000', 'USD', '175000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '185000', 'USD', '185000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '140000', 'USD', '140000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '45000', 'EUR', '48289', 'ES', '0', 'ES', 'M\n2023', 'SE', 'FT', 'Data Scientist', '36000', 'EUR', '38631', 'ES', '0', 'ES', 'M\n2023', 'SE', 'FT', 'Data Scientist', '105000', 'USD', '105000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '70000', 'USD', '70000', 'US', '0', 'US', 'M\n2023', 'EN', 'FT', 'Machine Learning Engineer', '163196', 'USD', '163196', 'US', '0', 'US', 'M\n2023', 'EN', 'FT', 'Machine Learning Engineer', '145885', 'USD', '145885', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '217000', 'USD', '217000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '185000', 'USD', '185000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Analyst', '202800', 'USD', '202800', 'US', '0', 'US', 'L\n2023', 'SE', 'FT', 'Data Analyst', '104300', 'USD', '104300', 'US', '0', 'US', 'L\n2023', 'SE', 'FT', 'Data Analyst', '145000', 'USD', '145000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Analyst', '65000', 'USD', '65000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '165000', 'USD', '165000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '132300', 'USD', '132300', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '179170', 'USD', '179170', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '94300', 'USD', '94300', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Analytics Engineer', '152500', 'USD', '152500', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Analytics Engineer', '116450', 'USD', '116450', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '247300', 'USD', '247300', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '133800', 'USD', '133800', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Research Engineer', '203000', 'USD', '203000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Research Engineer', '133000', 'USD', '133000', 'US', '0', 'US', 'M\n2023', 'EN', 'FT', 'Research Scientist', '220000', 'USD', '220000', 'US', '50', 'US', 'L\n2022', 'EN', 'FT', 'Machine Learning Engineer', '54000', 'CHF', '56536', 'CH', '100', 'CH', 'S\n2023', 'SE', 'FT', 'Data Scientist', '150000', 'USD', '150000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '120000', 'USD', '120000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Analytics Engineer', '289800', 'USD', '289800', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Analytics Engineer', '214000', 'USD', '214000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Analytics Engineer', '179820', 'USD', '179820', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Analytics Engineer', '143860', 'USD', '143860', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Machine Learning Engineer', '283200', 'USD', '283200', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Machine Learning Engineer', '188800', 'USD', '188800', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Analytics Engineer', '289800', 'USD', '289800', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Analytics Engineer', '214200', 'USD', '214200', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '185900', 'USD', '185900', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '129300', 'USD', '129300', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '252000', 'USD', '252000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '129000', 'USD', '129000', 'US', '0', 'US', 'M\n2023', 'MI', 'FT', 'Data Analytics Manager', '155000', 'USD', '155000', 'US', '0', 'US', 'M\n2023', 'MI', 'FT', 'Data Analytics Manager', '140000', 'USD', '140000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '161800', 'USD', '161800', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '141600', 'USD', '141600', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Machine Learning Engineer', '342300', 'USD', '342300', 'US', '0', 'US', 'L\n2023', 'SE', 'FT', 'Machine Learning Engineer', '176100', 'USD', '176100', 'US', '0', 'US', 'L\n2023', 'MI', 'FT', 'Data Engineer', '100000', 'USD', '100000', 'US', '100', 'US', 'M\n2023', 'MI', 'FT', 'Data Engineer', '70000', 'USD', '70000', 'US', '100', 'US', 'M\n2023', 'EN', 'FT', 'Data Engineer', '85000', 'USD', '85000', 'US', '0', 'US', 'M\n2023', 'EN', 'FT', 'Data Engineer', '65000', 'USD', '65000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '138784', 'USD', '138784', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '83270', 'USD', '83270', 'US', '100', 'US', 'M\n2023', 'EN', 'FT', 'Data Analyst', '75000', 'USD', '75000', 'US', '0', 'US', 'M\n2023', 'EN', 'FT', 'Data Analyst', '70000', 'USD', '70000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Analyst', '204500', 'USD', '204500', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Analyst', '138900', 'USD', '138900', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Machine Learning Engineer', '318300', 'USD', '318300', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Machine Learning Engineer', '212200', 'USD', '212200', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '95000', 'USD', '95000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '75000', 'USD', '75000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '195000', 'USD', '195000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '160000', 'USD', '160000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Analytics Engineer', '230000', 'USD', '230000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Analytics Engineer', '143200', 'USD', '143200', 'US', '0', 'US', 'M\n2023', 'MI', 'FT', 'Data Engineer', '100000', 'USD', '100000', 'US', '100', 'US', 'M\n2023', 'MI', 'FT', 'Data Engineer', '70000', 'USD', '70000', 'US', '100', 'US', 'M\n2023', 'MI', 'FT', 'Business Data Analyst', '105000', 'USD', '105000', 'US', '50', 'US', 'L\n2023', 'MI', 'FT', 'Applied Data Scientist', '1700000', 'INR', '20670', 'IN', '100', 'IN', 'L\n2023', 'MI', 'FT', 'Data Analyst', '38000', 'GBP', '46178', 'GB', '0', 'GB', 'M\n2023', 'MI', 'FT', 'Data Analyst', '35000', 'GBP', '42533', 'GB', '0', 'GB', 'M\n2023', 'SE', 'FT', 'Data Engineer', '145000', 'USD', '145000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '115000', 'USD', '115000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Analyst', '168400', 'USD', '168400', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Analyst', '105200', 'USD', '105200', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Applied Scientist', '309400', 'USD', '309400', 'US', '0', 'US', 'L\n2023', 'SE', 'FT', 'Applied Scientist', '159100', 'USD', '159100', 'US', '0', 'US', 'L\n2023', 'SE', 'FT', 'Machine Learning Engineer', '190000', 'USD', '190000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Machine Learning Engineer', '150000', 'USD', '150000', 'US', '0', 'US', 'M\n2023', 'MI', 'FT', 'Data Engineer', '162500', 'USD', '162500', 'US', '0', 'US', 'M\n2023', 'MI', 'FT', 'Data Engineer', '130000', 'USD', '130000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Analytics Engineer', '150000', 'USD', '150000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Analytics Engineer', '120000', 'USD', '120000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '145000', 'USD', '145000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '120000', 'USD', '120000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Applied Scientist', '222200', 'USD', '222200', 'US', '0', 'US', 'L\n2023', 'SE', 'FT', 'Applied Scientist', '136000', 'USD', '136000', 'US', '0', 'US', 'L\n2023', 'SE', 'FT', 'Data Analyst', '45000', 'GBP', '54685', 'CF', '100', 'CF', 'M\n2023', 'SE', 'FT', 'Data Analyst', '35000', 'GBP', '42533', 'CF', '100', 'CF', 'M\n2023', 'SE', 'FT', 'Data Engineer', '241000', 'USD', '241000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '155000', 'USD', '155000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '220000', 'USD', '220000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '190000', 'USD', '190000', 'US', '100', 'US', 'M\n2023', 'MI', 'FT', 'Data Scientist', '55000', 'GBP', '66837', 'GB', '0', 'GB', 'M\n2023', 'MI', 'FT', 'Data Scientist', '45000', 'GBP', '54685', 'GB', '0', 'GB', 'M\n2020', 'EX', 'FT', 'Staff Data Analyst', '15000', 'USD', '15000', 'NG', '0', 'CA', 'M\n2023', 'MI', 'FT', 'ETL Engineer', '70000', 'GBP', '85066', 'GB', '100', 'GB', 'M\n2023', 'MI', 'FT', 'ETL Engineer', '47500', 'GBP', '57723', 'GB', '100', 'GB', 'M\n2023', 'EN', 'FT', 'Data Analyst', '85000', 'USD', '85000', 'US', '100', 'US', 'M\n2023', 'EN', 'FT', 'Data Analyst', '75000', 'USD', '75000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '160000', 'USD', '160000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '140000', 'USD', '140000', 'US', '0', 'US', 'M\n2023', 'MI', 'FT', 'Machine Learning Engineer', '300000', 'USD', '300000', 'US', '0', 'US', 'M\n2023', 'MI', 'FT', 'Machine Learning Engineer', '250000', 'USD', '250000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '228000', 'USD', '228000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '186000', 'USD', '186000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '190000', 'USD', '190000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '170000', 'USD', '170000', 'US', '0', 'US', 'M\n2023', 'MI', 'FT', 'Research Engineer', '230000', 'USD', '230000', 'US', '0', 'US', 'M\n2023', 'MI', 'FT', 'Research Engineer', '200000', 'USD', '200000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Architect', '180000', 'USD', '180000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Architect', '115000', 'USD', '115000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Architect', '200000', 'USD', '200000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Architect', '115000', 'USD', '115000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data DevOps Engineer', '50000', 'EUR', '53654', 'FR', '50', 'FR', 'S\n2023', 'EX', 'FT', 'Data Engineer', '220000', 'USD', '220000', 'US', '0', 'US', 'M\n2023', 'EX', 'FT', 'Data Engineer', '205000', 'USD', '205000', 'US', '0', 'US', 'M\n2023', 'MI', 'FT', 'Data Engineer', '180000', 'USD', '180000', 'US', '0', 'US', 'M\n2023', 'MI', 'FT', 'Data Engineer', '130000', 'USD', '130000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '200000', 'USD', '200000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '150000', 'USD', '150000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Computer Vision Engineer', '215000', 'USD', '215000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Computer Vision Engineer', '170000', 'USD', '170000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Machine Learning Engineer', '247500', 'USD', '247500', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Machine Learning Engineer', '172200', 'USD', '172200', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Scientist', '224000', 'USD', '224000', 'CA', '0', 'CA', 'M\n2023', 'SE', 'FT', 'Data Scientist', '176000', 'USD', '176000', 'CA', '0', 'CA', 'M\n2023', 'SE', 'FT', 'Data Analyst', '120000', 'USD', '120000', 'US', '100', 'US', 'M\n2023', 'SE', 'FT', 'Data Analyst', '75000', 'USD', '75000', 'US', '100', 'US', 'M\n2023', 'EN', 'FT', 'Data Engineer', '1400000', 'INR', '17022', 'IN', '100', 'IN', 'L\n2023', 'SE', 'FT', 'Applied Data Scientist', '100000', 'AUD', '68318', 'AU', '100', 'FI', 'M\n2023', 'MI', 'FT', 'AI Developer', '100000', 'SGD', '75020', 'FI', '0', 'FI', 'M\n2023', 'SE', 'FT', 'Data Analyst', '140000', 'USD', '140000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Analyst', '120000', 'USD', '120000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '128000', 'USD', '128000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '81500', 'USD', '81500', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '145000', 'USD', '145000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '115000', 'USD', '115000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data Engineer', '185000', 'USD', '185000', 'US', '0', 'US', 'M\n2023', 'SE', 'FT', 'Data 

Well, now we have even more problems.
* The data is in a single long list and that is still hard to draw insights from.
* The newline characters ```\n``` corrupts our data

What if we want to get our data as a list of lists? - Each row is a list, in one big list.
The newline characters, ```\n```, that seperates rows, should tell our program to create a new list.

Well, we can do this manually, but this is tedious. Someone had already done all the heavy lifting for us by creating the ```csv``` module.

## CSV Reader
---

How can available CSV methods help us solve the problem we initially created? It's great that we can read CSV files using Python, but how can we get them from a string into a powerful list of lists that we can analyze? First, we need to import the csv module.

In [44]:
import csv

Then we open out file as usual, but this time, we read it using csv's ```reader()``` function as opposed to using Python's inbuilt ```.read()``` method. This helps us achieve our goal of getting a list of list since this function goes through all the rows, each new row being made a list. Observe:

In [45]:
with open("ds_salaries.csv") as f:
    csv_object = csv.reader(f)
    list_of_lists = list(csv_object)
    
print(list_of_lists)

[['work_year', 'experience_level', 'employment_type', 'job_title', 'salary', 'salary_currency', 'salary_in_usd', 'employee_residence', 'remote_ratio', 'company_location', 'company_size'], ['2023', 'SE', 'FT', 'Principal Data Scientist', '80000', 'EUR', '85847', 'ES', '100', 'ES', 'L'], ['2023', 'MI', 'CT', 'ML Engineer', '30000', 'USD', '30000', 'US', '100', 'US', 'S'], ['2023', 'MI', 'CT', 'ML Engineer', '25500', 'USD', '25500', 'US', '100', 'US', 'S'], ['2023', 'SE', 'FT', 'Data Scientist', '175000', 'USD', '175000', 'CA', '100', 'CA', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '120000', 'USD', '120000', 'CA', '100', 'CA', 'M'], ['2023', 'SE', 'FT', 'Applied Scientist', '222200', 'USD', '222200', 'US', '0', 'US', 'L'], ['2023', 'SE', 'FT', 'Applied Scientist', '136000', 'USD', '136000', 'US', '0', 'US', 'L'], ['2023', 'SE', 'FT', 'Data Scientist', '219000', 'USD', '219000', 'CA', '0', 'CA', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '141000', 'USD', '141000', 'CA', '0', 'CA', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '147100', 'USD', '147100', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '90700', 'USD', '90700', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Analyst', '130000', 'USD', '130000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Analyst', '100000', 'USD', '100000', 'US', '100', 'US', 'M'], ['2023', 'EN', 'FT', 'Applied Scientist', '213660', 'USD', '213660', 'US', '0', 'US', 'L'], ['2023', 'EN', 'FT', 'Applied Scientist', '130760', 'USD', '130760', 'US', '0', 'US', 'L'], ['2023', 'SE', 'FT', 'Data Modeler', '147100', 'USD', '147100', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Modeler', '90700', 'USD', '90700', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '170000', 'USD', '170000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '150000', 'USD', '150000', 'US', '0', 'US', 'M'], ['2023', 'MI', 'FT', 'Data Analyst', '150000', 'USD', '150000', 'US', '100', 'US', 'M'], ['2023', 'MI', 'FT', 'Data Analyst', '110000', 'USD', '110000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Research Engineer', '275000', 'USD', '275000', 'DE', '0', 'DE', 'M'], ['2023', 'SE', 'FT', 'Research Engineer', '174000', 'USD', '174000', 'DE', '0', 'DE', 'M'], ['2023', 'SE', 'FT', 'Analytics Engineer', '230000', 'USD', '230000', 'GB', '100', 'GB', 'M'], ['2023', 'SE', 'FT', 'Analytics Engineer', '143200', 'USD', '143200', 'GB', '100', 'GB', 'M'], ['2023', 'SE', 'FT', 'Business Intelligence Engineer', '225000', 'USD', '225000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Business Intelligence Engineer', '156400', 'USD', '156400', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Machine Learning Engineer', '200000', 'USD', '200000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Machine Learning Engineer', '130000', 'USD', '130000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Strategist', '90000', 'USD', '90000', 'CA', '0', 'CA', 'M'], ['2023', 'SE', 'FT', 'Data Strategist', '72000', 'USD', '72000', 'CA', '0', 'CA', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '253200', 'USD', '253200', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '90700', 'USD', '90700', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Computer Vision Engineer', '342810', 'USD', '342810', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Computer Vision Engineer', '184590', 'USD', '184590', 'US', '0', 'US', 'M'], ['2023', 'MI', 'FT', 'Data Engineer', '162500', 'USD', '162500', 'US', '0', 'US', 'M'], ['2023', 'MI', 'FT', 'Data Engineer', '130000', 'USD', '130000', 'US', '0', 'US', 'M'], ['2023', 'MI', 'FT', 'Data Analyst', '105380', 'USD', '105380', 'US', '0', 'US', 'M'], ['2023', 'MI', 'FT', 'Data Analyst', '64500', 'USD', '64500', 'US', '0', 'US', 'M'], ['2023', 'EN', 'FT', 'Data Quality Analyst', '100000', 'USD', '100000', 'NG', '100', 'NG', 'L'], ['2023', 'EN', 'FT', 'Compliance Data Analyst', '30000', 'USD', '30000', 'NG', '100', 'NG', 'L'], ['2022', 'MI', 'FT', 'Machine Learning Engineer', '1650000', 'INR', '20984', 'IN', '50', 'IN', 'L'], ['2023', 'EN', 'FT', 'Applied Scientist', '204620', 'USD', '204620', 'US', '0', 'US', 'L'], ['2023', 'EN', 'FT', 'Applied Scientist', '110680', 'USD', '110680', 'US', '0', 'US', 'L'], ['2023', 'SE', 'FT', 'Data Engineer', '270703', 'USD', '270703', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '221484', 'USD', '221484', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '212750', 'USD', '212750', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '185000', 'USD', '185000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '262000', 'USD', '262000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '245000', 'USD', '245000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '275300', 'USD', '275300', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '183500', 'USD', '183500', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '218500', 'USD', '218500', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '199098', 'USD', '199098', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '203300', 'USD', '203300', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '123600', 'USD', '123600', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Research Engineer', '189110', 'USD', '189110', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Research Engineer', '139000', 'USD', '139000', 'US', '0', 'US', 'M'], ['2023', 'EX', 'FT', 'Data Scientist', '258750', 'USD', '258750', 'US', '0', 'US', 'M'], ['2023', 'EX', 'FT', 'Data Scientist', '185000', 'USD', '185000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '231500', 'USD', '231500', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '166000', 'USD', '166000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '172500', 'USD', '172500', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '110500', 'USD', '110500', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '238000', 'USD', '238000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '176000', 'USD', '176000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '237000', 'USD', '237000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '201450', 'USD', '201450', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Applied Scientist', '309400', 'USD', '309400', 'US', '0', 'US', 'L'], ['2023', 'SE', 'FT', 'Applied Scientist', '159100', 'USD', '159100', 'US', '0', 'US', 'L'], ['2023', 'SE', 'FT', 'Data Engineer', '115000', 'USD', '115000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '81500', 'USD', '81500', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '237000', 'USD', '237000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '201450', 'USD', '201450', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Computer Vision Engineer', '280000', 'USD', '280000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Computer Vision Engineer', '210000', 'USD', '210000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Architect', '280100', 'USD', '280100', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Architect', '168100', 'USD', '168100', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '193500', 'USD', '193500', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '139000', 'USD', '139000', 'US', '100', 'US', 'M'], ['2023', 'MI', 'FT', 'Data Scientist', '510000', 'HKD', '65062', 'HK', '0', 'HK', 'L'], ['2023', 'SE', 'FT', 'Machine Learning Engineer', '150000', 'USD', '150000', 'PT', '100', 'US', 'M'], ['2023', 'MI', 'FT', 'Applied Machine Learning Engineer', '65000', 'EUR', '69751', 'IN', '100', 'DE', 'S'], ['2022', 'EN', 'FT', 'AI Developer', '300000', 'USD', '300000', 'IN', '50', 'IN', 'L'], ['2023', 'MI', 'FT', 'Machine Learning Engineer', '90000', 'EUR', '96578', 'NL', '100', 'NL', 'L'], ['2023', 'SE', 'FT', 'Business Intelligence Engineer', '185900', 'USD', '185900', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Business Intelligence Engineer', '129300', 'USD', '129300', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '225000', 'USD', '225000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '175000', 'USD', '175000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '185000', 'USD', '185000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '140000', 'USD', '140000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '45000', 'EUR', '48289', 'ES', '0', 'ES', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '36000', 'EUR', '38631', 'ES', '0', 'ES', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '105000', 'USD', '105000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '70000', 'USD', '70000', 'US', '0', 'US', 'M'], ['2023', 'EN', 'FT', 'Machine Learning Engineer', '163196', 'USD', '163196', 'US', '0', 'US', 'M'], ['2023', 'EN', 'FT', 'Machine Learning Engineer', '145885', 'USD', '145885', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '217000', 'USD', '217000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '185000', 'USD', '185000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Analyst', '202800', 'USD', '202800', 'US', '0', 'US', 'L'], ['2023', 'SE', 'FT', 'Data Analyst', '104300', 'USD', '104300', 'US', '0', 'US', 'L'], ['2023', 'SE', 'FT', 'Data Analyst', '145000', 'USD', '145000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Analyst', '65000', 'USD', '65000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '165000', 'USD', '165000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '132300', 'USD', '132300', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '179170', 'USD', '179170', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '94300', 'USD', '94300', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Analytics Engineer', '152500', 'USD', '152500', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Analytics Engineer', '116450', 'USD', '116450', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '247300', 'USD', '247300', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '133800', 'USD', '133800', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Research Engineer', '203000', 'USD', '203000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Research Engineer', '133000', 'USD', '133000', 'US', '0', 'US', 'M'], ['2023', 'EN', 'FT', 'Research Scientist', '220000', 'USD', '220000', 'US', '50', 'US', 'L'], ['2022', 'EN', 'FT', 'Machine Learning Engineer', '54000', 'CHF', '56536', 'CH', '100', 'CH', 'S'], ['2023', 'SE', 'FT', 'Data Scientist', '150000', 'USD', '150000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '120000', 'USD', '120000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Analytics Engineer', '289800', 'USD', '289800', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Analytics Engineer', '214000', 'USD', '214000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Analytics Engineer', '179820', 'USD', '179820', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Analytics Engineer', '143860', 'USD', '143860', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Machine Learning Engineer', '283200', 'USD', '283200', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Machine Learning Engineer', '188800', 'USD', '188800', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Analytics Engineer', '289800', 'USD', '289800', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Analytics Engineer', '214200', 'USD', '214200', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '185900', 'USD', '185900', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '129300', 'USD', '129300', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '252000', 'USD', '252000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '129000', 'USD', '129000', 'US', '0', 'US', 'M'], ['2023', 'MI', 'FT', 'Data Analytics Manager', '155000', 'USD', '155000', 'US', '0', 'US', 'M'], ['2023', 'MI', 'FT', 'Data Analytics Manager', '140000', 'USD', '140000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '161800', 'USD', '161800', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '141600', 'USD', '141600', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Machine Learning Engineer', '342300', 'USD', '342300', 'US', '0', 'US', 'L'], ['2023', 'SE', 'FT', 'Machine Learning Engineer', '176100', 'USD', '176100', 'US', '0', 'US', 'L'], ['2023', 'MI', 'FT', 'Data Engineer', '100000', 'USD', '100000', 'US', '100', 'US', 'M'], ['2023', 'MI', 'FT', 'Data Engineer', '70000', 'USD', '70000', 'US', '100', 'US', 'M'], ['2023', 'EN', 'FT', 'Data Engineer', '85000', 'USD', '85000', 'US', '0', 'US', 'M'], ['2023', 'EN', 'FT', 'Data Engineer', '65000', 'USD', '65000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '138784', 'USD', '138784', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '83270', 'USD', '83270', 'US', '100', 'US', 'M'], ['2023', 'EN', 'FT', 'Data Analyst', '75000', 'USD', '75000', 'US', '0', 'US', 'M'], ['2023', 'EN', 'FT', 'Data Analyst', '70000', 'USD', '70000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Analyst', '204500', 'USD', '204500', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Analyst', '138900', 'USD', '138900', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Machine Learning Engineer', '318300', 'USD', '318300', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Machine Learning Engineer', '212200', 'USD', '212200', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '95000', 'USD', '95000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '75000', 'USD', '75000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '195000', 'USD', '195000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '160000', 'USD', '160000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Analytics Engineer', '230000', 'USD', '230000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Analytics Engineer', '143200', 'USD', '143200', 'US', '0', 'US', 'M'], ['2023', 'MI', 'FT', 'Data Engineer', '100000', 'USD', '100000', 'US', '100', 'US', 'M'], ['2023', 'MI', 'FT', 'Data Engineer', '70000', 'USD', '70000', 'US', '100', 'US', 'M'], ['2023', 'MI', 'FT', 'Business Data Analyst', '105000', 'USD', '105000', 'US', '50', 'US', 'L'], ['2023', 'MI', 'FT', 'Applied Data Scientist', '1700000', 'INR', '20670', 'IN', '100', 'IN', 'L'], ['2023', 'MI', 'FT', 'Data Analyst', '38000', 'GBP', '46178', 'GB', '0', 'GB', 'M'], ['2023', 'MI', 'FT', 'Data Analyst', '35000', 'GBP', '42533', 'GB', '0', 'GB', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '145000', 'USD', '145000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '115000', 'USD', '115000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Analyst', '168400', 'USD', '168400', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Analyst', '105200', 'USD', '105200', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Applied Scientist', '309400', 'USD', '309400', 'US', '0', 'US', 'L'], ['2023', 'SE', 'FT', 'Applied Scientist', '159100', 'USD', '159100', 'US', '0', 'US', 'L'], ['2023', 'SE', 'FT', 'Machine Learning Engineer', '190000', 'USD', '190000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Machine Learning Engineer', '150000', 'USD', '150000', 'US', '0', 'US', 'M'], ['2023', 'MI', 'FT', 'Data Engineer', '162500', 'USD', '162500', 'US', '0', 'US', 'M'], ['2023', 'MI', 'FT', 'Data Engineer', '130000', 'USD', '130000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Analytics Engineer', '150000', 'USD', '150000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Analytics Engineer', '120000', 'USD', '120000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '145000', 'USD', '145000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '120000', 'USD', '120000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Applied Scientist', '222200', 'USD', '222200', 'US', '0', 'US', 'L'], ['2023', 'SE', 'FT', 'Applied Scientist', '136000', 'USD', '136000', 'US', '0', 'US', 'L'], ['2023', 'SE', 'FT', 'Data Analyst', '45000', 'GBP', '54685', 'CF', '100', 'CF', 'M'], ['2023', 'SE', 'FT', 'Data Analyst', '35000', 'GBP', '42533', 'CF', '100', 'CF', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '241000', 'USD', '241000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '155000', 'USD', '155000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '220000', 'USD', '220000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '190000', 'USD', '190000', 'US', '100', 'US', 'M'], ['2023', 'MI', 'FT', 'Data Scientist', '55000', 'GBP', '66837', 'GB', '0', 'GB', 'M'], ['2023', 'MI', 'FT', 'Data Scientist', '45000', 'GBP', '54685', 'GB', '0', 'GB', 'M'], ['2020', 'EX', 'FT', 'Staff Data Analyst', '15000', 'USD', '15000', 'NG', '0', 'CA', 'M'], ['2023', 'MI', 'FT', 'ETL Engineer', '70000', 'GBP', '85066', 'GB', '100', 'GB', 'M'], ['2023', 'MI', 'FT', 'ETL Engineer', '47500', 'GBP', '57723', 'GB', '100', 'GB', 'M'], ['2023', 'EN', 'FT', 'Data Analyst', '85000', 'USD', '85000', 'US', '100', 'US', 'M'], ['2023', 'EN', 'FT', 'Data Analyst', '75000', 'USD', '75000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '160000', 'USD', '160000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '140000', 'USD', '140000', 'US', '0', 'US', 'M'], ['2023', 'MI', 'FT', 'Machine Learning Engineer', '300000', 'USD', '300000', 'US', '0', 'US', 'M'], ['2023', 'MI', 'FT', 'Machine Learning Engineer', '250000', 'USD', '250000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '228000', 'USD', '228000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '186000', 'USD', '186000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '190000', 'USD', '190000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '170000', 'USD', '170000', 'US', '0', 'US', 'M'], ['2023', 'MI', 'FT', 'Research Engineer', '230000', 'USD', '230000', 'US', '0', 'US', 'M'], ['2023', 'MI', 'FT', 'Research Engineer', '200000', 'USD', '200000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Architect', '180000', 'USD', '180000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Architect', '115000', 'USD', '115000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Architect', '200000', 'USD', '200000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Architect', '115000', 'USD', '115000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data DevOps Engineer', '50000', 'EUR', '53654', 'FR', '50', 'FR', 'S'], ['2023', 'EX', 'FT', 'Data Engineer', '220000', 'USD', '220000', 'US', '0', 'US', 'M'], ['2023', 'EX', 'FT', 'Data Engineer', '205000', 'USD', '205000', 'US', '0', 'US', 'M'], ['2023', 'MI', 'FT', 'Data Engineer', '180000', 'USD', '180000', 'US', '0', 'US', 'M'], ['2023', 'MI', 'FT', 'Data Engineer', '130000', 'USD', '130000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '200000', 'USD', '200000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Engineer', '150000', 'USD', '150000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Computer Vision Engineer', '215000', 'USD', '215000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Computer Vision Engineer', '170000', 'USD', '170000', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Machine Learning Engineer', '247500', 'USD', '247500', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Machine Learning Engineer', '172200', 'USD', '172200', 'US', '0', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '224000', 'USD', '224000', 'CA', '0', 'CA', 'M'], ['2023', 'SE', 'FT', 'Data Scientist', '176000', 'USD', '176000', 'CA', '0', 'CA', 'M'], ['2023', 'SE', 'FT', 'Data Analyst', '120000', 'USD', '120000', 'US', '100', 'US', 'M'], ['2023', 'SE', 'FT', 'Data Analyst', '75000', 'USD', '75000', 'US', '100', 'US', 'M'], 

The ```reader()``` function reads the file but instead of returning a string, it returns a csv object. To turn this into a list of lists, we just need to call on the list function on this csv object. Now we can draw meaningful insights from this data. That's it for now.

# Data Analysis in Base Python

---

Alright, now that we know how to work with CSV files, let's actually draw some insights from this data without the use of any third party libraries. I'm curious to know:
1. Salaries:
    - What's the average salary of a data scientist?
        - What's their average salary in each year?
    - In which year were data scientists paid the most and vice versa?
        - Which year had the single highest salary and vice versa?
    - How do the salaries differ? Measure their spread:
        - Overally
        - In each year
        - In each experience level
        - In each experience level in each year
2. Experience:
    - Which experience level has the highest & lowest average salary?
        - Which experience level had the highest & lowest salary in each year?
3. Employment Type:
    - Which employment type has the highest and lowest average salaries?
        - Which employment type has the highest and lowest average salaries in each year?
4. Job Titles (Roles):
    - How many job titles does the realm of data science have? And which one has the highest average salary?
        - Which role has the highest & lowest paying salary?
        - Which role has the highest & lowest average paying salary in each year?
5. Currency:
    - Which currency paid data scientists the most and least averagely?
        - Which currency paid data scientists the most and least averagely in each year?
6. Employee Residence:
    - Where do the highest and least paid data scientiests reside averagely?
        - How does this vary from year to year (if at all it does)?
7. Remote Ratio:
    - How many data scientists work fully remote, fully in office and hybrid? How do their average salaries compare?
        - How do their salaries compare in each year?
8. Company Location:
    - Where are the companies that averagely pay the most & least located?
        - How does this vary from year to year?
9. Company Size:
    - Which company size pays the most and least averagely?
        - How do the average salaries of each company size compare in each year?

In [46]:
# Import Statements:
from ProbStatipy import central, spread

Wait a minute! Hold up!

![Hold up meme: A drawing of a cartoon stretching its hands signaling the viewer to stop with the caption "Wait a minute, Hold Up"](https://th.bing.com/th/id/OIP.UjDCCX5rd_2CFE7gFXxyDwHaFX?w=285&h=206&c=7&r=0&o=5&dpr=1.5&pid=1.7)

I thought we was doing analysis using raw Python! Why you importing weird modules for?

Let me explain. [`ProbStatipy`](https://github.com/0gregory0/ProbStatipy) is my package. I made it in base Python and published it on [PyPI](https://pypi.org/project/ProbStatipy/). It relies on `math`, a module in the Python Standard Library. It contains functions to measure central tendancies such as mean, median and mode, and dispersion such as variance, standard deviation, mean absolute deviation, range and interquartile range.

I figured that there's no need to rewrite these functions when I can actually reuse my own. Now that that's out of the way, let's continue.

We can start by farmiliarizing ourselves with the data.

In [47]:
# Reopening the csv file
with open("ds_salaries.csv") as f:
    csv_object = csv.reader(f)
    data = list(csv_object)

# Printing out the first 5 rows
print(data[:5])

[['work_year', 'experience_level', 'employment_type', 'job_title', 'salary', 'salary_currency', 'salary_in_usd', 'employee_residence', 'remote_ratio', 'company_location', 'company_size'], ['2023', 'SE', 'FT', 'Principal Data Scientist', '80000', 'EUR', '85847', 'ES', '100', 'ES', 'L'], ['2023', 'MI', 'CT', 'ML Engineer', '30000', 'USD', '30000', 'US', '100', 'US', 'S'], ['2023', 'MI', 'CT', 'ML Engineer', '25500', 'USD', '25500', 'US', '100', 'US', 'S'], ['2023', 'SE', 'FT', 'Data Scientist', '175000', 'USD', '175000', 'CA', '100', 'CA', 'M']]

## Preparing / Cleaning the Data
Before we start analyzing the data, we must first clean it and make it ready for the analysis ahead.

In [48]:
# separating the title row from the rows containing the actual data
title_row = data[0]
data_rows = data[1:]

# Changing the numerical columns into numerical values:

## 'work_year' should be ints
work_year_index = title_row.index('work_year') # getting the index of the 'work_year' column

for row in data_rows:
    row[0] = int(row[0])

## 'salary' should be float
salary_index = title_row.index('salary') # getting the index of the 'salary' column

for row in data_rows:
    row[salary_index] = float(row[salary_index])

## 'salary_in_usd' should be float
usd_salary_index = title_row.index("salary_in_usd") # getting the index of the 'salary_in_usd' column

for row in data_rows:
    row[usd_salary_index] = float(row[usd_salary_index])

## 'remote_ratio' should be int
remote_ratio_index = title_row.index('remote_ratio') # getting the index of the 'remote_ratio_index' column

for row in data_rows:
    row[remote_ratio_index] = int(row[remote_ratio_index])

## Analyzing the Data.
Finally, let's draw some insights!

### 1. Salaries
#### The average salary of a data scientist.
For this, and the rest of the questions, we'll analyse the salary in USD (`salary_in_usd`) column because having a uniform currency will help us draw reasonable insights.

In [49]:
# creating a list of salaries to get their means
salaries = []

for row in data_rows:
    salaries.append(row[usd_salary_index]) # changing them from strings to floats

# getting the average salary of a data scientist
avg_salary = central.mean(salaries)
avg_salary_rounded = round(avg_salary)

print(avg_salary)
print(avg_salary_rounded)

137570.38988015978
137570

#### The average salary for each year
To get this, we must first get all the years that are in our data, then compute the mean for each year.

In [50]:
#### Getting all the years in our data ####
#### --------------------------------- ####

# "work_years" is the first column of the data with index [0]

# Getting the unique list of years
years = []
for row in data_rows:
    if row[0] in years:
        continue
    else:
        years.append(row[0])

# Sorting the unique list of years
years.sort()

print(years)

[2020, 2021, 2022, 2023]

In [51]:
#### Computing the average salaries for each year ####
#### -------------------------------------------- ####

# for the year 2020:
salaries_2020 = []
for row in data_rows:
    if 2020 in row:
        salaries_2020.append(row[usd_salary_index])

avg_sal_2020 = central.mean(salaries_2020)
avg_sal_2020_rounded = round(avg_sal_2020)

# for the year 2021:
salaries_2021 = []
for row in data_rows:
    if 2021 in row:
        salaries_2021.append(row[usd_salary_index])

avg_sal_2021 = central.mean(salaries_2021)
avg_sal_2021_rounded = round(avg_sal_2021)

# for the year 2022:
salaries_2022 = []
for row in data_rows:
    if 2022 in row:
        salaries_2022.append(row[usd_salary_index])

avg_sal_2022 = central.mean(salaries_2022)
avg_sal_2022_rounded = round(avg_sal_2022)

# for the year 2023:
salaries_2023 = []
for row in data_rows:
    if 2023 in row:
        salaries_2023.append(row[usd_salary_index])

avg_sal_2023 = central.mean(salaries_2023)
avg_sal_2023_rounded = round(avg_sal_2023)

print(avg_sal_2020)
print(avg_sal_2020_rounded)
print('')

print(avg_sal_2021)
print(avg_sal_2021_rounded)
print('')

print(avg_sal_2022)
print(avg_sal_2022_rounded)
print('')

print(avg_sal_2023)
print(avg_sal_2023_rounded)

92302.63157894737
92303

94087.20869565217
94087

133338.62079326922
133339

149045.54117647058
149046

#### Highest & Lowest Salary Recorded
Getting this will help us answer questions such as:
> "Which year had the single highest salary and vice versa?"

We get the highest and lowest salaries by using our list of salaries. We can then pin these salaries to their respective rows and draw insights.

In [52]:
# Determining the highest and lowest salary ever recorded
highest_salary = max(salaries)
lowest_salary = min(salaries)

# Getting the row(s) where these salaries were recorded
highest_sal_rows = []
lowest_sal_rows = []
for row in data_rows:
    if highest_salary == row[usd_salary_index]:
        highest_sal_rows.append(row)
    elif lowest_salary == row[usd_salary_index]:
        lowest_sal_rows.append(row)
    else:
        pass

print(highest_salary)
print(highest_sal_rows)
print(f'{highest_sal_rows[0][0]} is the year with the highest salary ever recorded')
print('')

print(lowest_salary)
print(lowest_sal_rows)
print(f'{lowest_sal_rows[0][0]} is the year with the lowest salary ever recorded')

450000.0
[[2020, 'MI', 'FT', 'Research Scientist', 450000.0, 'USD', 450000.0, 'US', 0, 'US', 'M']]
2020 is the year with the highest salary ever recorded

5132.0
[[2022, 'MI', 'FT', 'NLP Engineer', 120000.0, 'CZK', 5132.0, 'CZ', 100, 'CZ', 'M']]
2022 is the year with the lowest salary ever recorded

#### Dispersion or spread of salaries
How are the salararies spread out:
- Overally
- In each year
- In each experience level
- In each experience level in each year

##### Overally

In [53]:
sal_stdev = spread.stdeviation(salaries)
sal_range = spread.get_range(salaries)
sal_iqr = spread.iqr(salaries)

print(f'''The salaries in this dataset have a:
      standard deviation of {sal_stdev} approx. {round(sal_stdev)}
      range of {sal_range}
      and an interquartile range of {sal_iqr}''')

The salaries in this dataset have a:
      standard deviation of 63047.22849740541 approx. 63047
      range of 444868.0
      and an interquartile range of 80000.0

###### Interpretation
**Range** is the difference between the highest and the lowest value in our data set. In this case, the difference between the highest and the lowest earner is `$444868.0`!

**Interquartile range** is the difference between the highest quartile (Q3) and the lowest quartile (Q1). It get's rid of outliers by dividing the data into 4 groups in ascending order, then disregarding the 1st and the last group when determining the range. Without the 25% of data from either side, difference between the highest and the lowest data point is `$80000.0`

            |----------------+----------------+----------------+---------------|
        starting    group   Q1      group     Q2    group      Q3   group   ending
        point         1               2    (median)   3               4     point

**Standard Deviation** shows us the average deviation from the mean. In our dataset, the average salary was `$137570`. The average difference between the mean and each datapoint is `$63047`. A high standard deviation, such as this, shows the uncertainty as to how much a data scientist's work is really valued at.

The standard deviation also comes in handy in determining usual and unusual values.
**Usual values** are those that lie within two standard deviations from the mean and **unusual values** are those that lie without.

    -----------------------+------------------------+------------------------+-----------------------
        <-  unusual      mean -       usual        mean       usual        mean +          unusual ->
            values      2(stdev)      values                  values      2(stdev)         values

Unusual values are the values that are least likely to occur and have a probability of 5% (.05) or less. Let's find out our unusual values.

In [54]:
upper_usual_limit = avg_salary + (2 * sal_stdev)
lower_usual_limit = avg_salary - (2 * sal_stdev)

print(f'The highest usual salary is{upper_usual_limit} and the lowest usual salary is {lower_usual_limit}')
print('')

low_unusual_sal = []
high_unusual_sal = []

for salary in salaries:
    if salary < lower_usual_limit:
        low_unusual_sal.append(salary)
        low_unusual_sal.sort()
    elif salary > upper_usual_limit:
        high_unusual_sal.append(salary)
        high_unusual_sal.sort()
    else:
        pass

unusual_sal = low_unusual_sal + high_unusual_sal

print(f'The unusual salaries are {unusual_sal}')
print('')

print(f'The unusually low salaries are {low_unusual_sal}')
print('')

print(f'The unusually high salaries are {high_unusual_sal}')

The highest usual salary is263664.8468749706 and the lowest usual salary is 11475.932885348957

The unusual salaries are [5132.0, 5409.0, 5409.0, 5679.0, 5707.0, 5723.0, 5882.0, 6072.0, 6072.0, 6270.0, 6304.0, 6359.0, 7000.0, 7500.0, 7799.0, 8000.0, 8000.0, 8050.0, 9272.0, 9289.0, 9466.0, 9727.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10354.0, 265000.0, 265000.0, 265000.0, 266400.0, 269000.0, 269600.0, 270000.0, 270703.0, 272000.0, 272550.0, 272550.0, 275000.0, 275000.0, 275000.0, 275000.0, 275000.0, 275000.0, 275300.0, 275300.0, 275300.0, 275300.0, 275300.0, 275300.0, 275300.0, 275300.0, 276000.0, 276000.0, 276000.0, 280000.0, 280100.0, 280700.0, 283200.0, 284000.0, 284310.0, 285800.0, 286000.0, 288000.0, 288000.0, 289076.0, 289076.0, 289800.0, 289800.0, 290000.0, 291500.0, 291500.0, 293000.0, 297300.0, 297300.0, 297300.0, 297300.0, 297500.0, 299500.0, 299500.0, 299500.0, 299500.0, 299500.0, 300000.0, 300000.0, 300000.0, 300000.0, 300000.0, 300000.0, 300000.0, 300000.0, 300000.0, 300000.0, 300000.0, 300240.0, 300240.0, 304000.0, 309400.0, 309400.0, 310000.0, 310000.0, 310000.0, 310000.0, 310000.0, 310000.0, 310000.0, 314100.0, 315000.0, 317070.0, 318300.0, 318300.0, 323300.0, 324000.0, 325000.0, 329500.0, 340000.0, 342300.0, 342810.0, 345600.0, 350000.0, 350000.0, 353200.0, 370000.0, 370000.0, 375000.0, 375000.0, 376080.0, 380000.0, 385000.0, 405000.0, 412000.0, 416000.0, 423000.0, 423834.0, 430967.0, 450000.0]

The unusually low salaries are [5132.0, 5409.0, 5409.0, 5679.0, 5707.0, 5723.0, 5882.0, 6072.0, 6072.0, 6270.0, 6304.0, 6359.0, 7000.0, 7500.0, 7799.0, 8000.0, 8000.0, 8050.0, 9272.0, 9289.0, 9466.0, 9727.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10354.0]

The unusually high salaries are [265000.0, 265000.0, 265000.0, 266400.0, 269000.0, 269600.0, 270000.0, 270703.0, 272000.0, 272550.0, 272550.0, 275000.0, 275000.0, 275000.0, 275000.0, 275000.0, 275000.0, 275300.0, 275300.0, 275300.0, 275300.0, 275300.0, 275300.0, 275300.0, 275300.0, 276000.0, 276000.0, 276000.0, 280000.0, 280100.0, 280700.0, 283200.0, 284000.0, 284310.0, 285800.0, 286000.0, 288000.0, 288000.0, 289076.0, 289076.0, 289800.0, 289800.0, 290000.0, 291500.0, 291500.0, 293000.0, 297300.0, 297300.0, 297300.0, 297300.0, 297500.0, 299500.0, 299500.0, 299500.0, 299500.0, 299500.0, 300000.0, 300000.0, 300000.0, 300000.0, 300000.0, 300000.0, 300000.0, 300000.0, 300000.0, 300000.0, 300000.0, 300240.0, 300240.0, 304000.0, 309400.0, 309400.0, 310000.0, 310000.0, 310000.0, 310000.0, 310000.0, 310000.0, 310000.0, 314100.0, 315000.0, 317070.0, 318300.0, 318300.0, 323300.0, 324000.0, 325000.0, 329500.0, 340000.0, 342300.0, 342810.0, 345600.0, 350000.0, 350000.0, 353200.0, 370000.0, 370000.0, 375000.0, 375000.0, 376080.0, 380000.0, 385000.0, 405000.0, 412000.0, 416000.0, 423000.0, 423834.0, 430967.0, 450000.0]

In [57]:
print(len(salaries))
print(len(unusual_sal))
print(0.05 * len(salaries))

3755
137
187.75

**Interpretation**

As mentioned earlier, it's normal to get that 5% or less of your data consists of unusual values. We have 3755 rows in our data set, therefore, we can expect at most 188 rows to contain unusual values. True to this fact, our dataset contains only 137 entries of unusual salaries. Unusual values are not bad, they are just less likely to occur.

The highest usual salary is approx. `263664` and the lowest usual salary is approx. `11475`. Therefore, it's unlikely, but not impossible, to get a data scientist earning below `$11,475` or above `$263,664`.